// Code generated by Fern. DO NOT EDIT.

package client

import (
	client "github.com/prism-api/sdk-go/api/client"
	core "github.com/prism-api/sdk-go/core"
	internal "github.com/prism-api/sdk-go/internal"
	option "github.com/prism-api/sdk-go/option"
)

type Client struct {
	API *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		API:     client.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
