// Code generated by Fern. DO NOT EDIT.

package dex

import (
	context "context"

	api "github.com/prism-api/sdk-go/api"
	solana "github.com/prism-api/sdk-go/api/solana"
	core "github.com/prism-api/sdk-go/core"
	internal "github.com/prism-api/sdk-go/internal"
	option "github.com/prism-api/sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns a wallet profile for a specific wallet.
func (c *Client) GetWalletProfile(
	ctx context.Context,
	request *solana.GetWalletProfileDexRequest,
	opts ...option.RequestOption,
) (*api.SolanaDexWalletProfile, error) {
	response, err := c.WithRawResponse.GetWalletProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter, query, and sort wallet profiles based on specified metrics and conditions.
func (c *Client) SearchWalletProfiles(
	ctx context.Context,
	request *solana.SearchWalletProfilesDexRequest,
	opts ...option.RequestOption,
) (*solana.SearchWalletProfilesDexResponse, error) {
	response, err := c.WithRawResponse.SearchWalletProfiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the profile for a specific token.
func (c *Client) GetTokenProfile(
	ctx context.Context,
	request *solana.GetTokenProfileDexRequest,
	opts ...option.RequestOption,
) (*api.SolanaDexTokenProfile, error) {
	response, err := c.WithRawResponse.GetTokenProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter, query, and sort token profiles based on specified metrics and conditions.
func (c *Client) SearchTokenProfiles(
	ctx context.Context,
	request *solana.SearchTokenProfilesDexRequest,
	opts ...option.RequestOption,
) (*solana.SearchTokenProfilesDexResponse, error) {
	response, err := c.WithRawResponse.SearchTokenProfiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns trades for a wallet, token or both.
func (c *Client) GetTrades(
	ctx context.Context,
	request *solana.GetTradesDexRequest,
	opts ...option.RequestOption,
) (*solana.GetTradesDexResponse, error) {
	response, err := c.WithRawResponse.GetTrades(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns swaps for a wallet, token or both.
func (c *Client) GetSwaps(
	ctx context.Context,
	request *solana.GetSwapsDexRequest,
	opts ...option.RequestOption,
) (*solana.GetSwapsDexResponse, error) {
	response, err := c.WithRawResponse.GetSwaps(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns prices for one or more tokens.
func (c *Client) GetPrice(
	ctx context.Context,
	request *solana.GetPriceDexRequest,
	opts ...option.RequestOption,
) ([]*api.SolanaDexPrice, error) {
	response, err := c.WithRawResponse.GetPrice(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price stats for one or more tokens.
func (c *Client) GetPriceStats(
	ctx context.Context,
	request *solana.GetPriceStatsDexRequest,
	opts ...option.RequestOption,
) ([]*api.SolanaDexPriceStats, error) {
	response, err := c.WithRawResponse.GetPriceStats(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price candles for a specific token.
func (c *Client) GetPriceCandles(
	ctx context.Context,
	request *solana.GetPriceCandlesDexRequest,
	opts ...option.RequestOption,
) ([]*api.SolanaDexPriceCandle, error) {
	response, err := c.WithRawResponse.GetPriceCandles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price history for one or more tokens.
func (c *Client) GetPriceHistory(
	ctx context.Context,
	request *solana.GetPriceHistoryDexRequest,
	opts ...option.RequestOption,
) ([]*api.SolanaDexPriceHistory, error) {
	response, err := c.WithRawResponse.GetPriceHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
