// Code generated by Fern. DO NOT EDIT.

package prism

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	subscribeTokenTradesFieldMethod = big.NewInt(1 << 0)
	subscribeTokenTradesFieldTopic  = big.NewInt(1 << 1)
	subscribeTokenTradesFieldParams = big.NewInt(1 << 2)
)

type SubscribeTokenTrades struct {
	Method string                      `json:"method" url:"method"`
	Topic  string                      `json:"topic" url:"topic"`
	Params *SubscribeTokenTradesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeTokenTrades) GetMethod() string {
	if s == nil {
		return ""
	}
	return s.Method
}

func (s *SubscribeTokenTrades) GetTopic() string {
	if s == nil {
		return ""
	}
	return s.Topic
}

func (s *SubscribeTokenTrades) GetParams() *SubscribeTokenTradesParams {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SubscribeTokenTrades) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeTokenTrades) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenTrades) SetMethod(method string) {
	s.Method = method
	s.require(subscribeTokenTradesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenTrades) SetTopic(topic string) {
	s.Topic = topic
	s.require(subscribeTokenTradesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenTrades) SetParams(params *SubscribeTokenTradesParams) {
	s.Params = params
	s.require(subscribeTokenTradesFieldParams)
}

func (s *SubscribeTokenTrades) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeTokenTrades
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeTokenTrades(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeTokenTrades) MarshalJSON() ([]byte, error) {
	type embed SubscribeTokenTrades
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeTokenTrades) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeTokenTradesParamsFieldTokens = big.NewInt(1 << 0)
)

type SubscribeTokenTradesParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeTokenTradesParams) GetTokens() []string {
	if s == nil {
		return nil
	}
	return s.Tokens
}

func (s *SubscribeTokenTradesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeTokenTradesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenTradesParams) SetTokens(tokens []string) {
	s.Tokens = tokens
	s.require(subscribeTokenTradesParamsFieldTokens)
}

func (s *SubscribeTokenTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeTokenTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeTokenTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeTokenTradesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeTokenTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeTokenTradesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeWalletTradesFieldMethod = big.NewInt(1 << 0)
	subscribeWalletTradesFieldTopic  = big.NewInt(1 << 1)
	subscribeWalletTradesFieldParams = big.NewInt(1 << 2)
)

type SubscribeWalletTrades struct {
	Method string                       `json:"method" url:"method"`
	Topic  string                       `json:"topic" url:"topic"`
	Params *SubscribeWalletTradesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeWalletTrades) GetMethod() string {
	if s == nil {
		return ""
	}
	return s.Method
}

func (s *SubscribeWalletTrades) GetTopic() string {
	if s == nil {
		return ""
	}
	return s.Topic
}

func (s *SubscribeWalletTrades) GetParams() *SubscribeWalletTradesParams {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SubscribeWalletTrades) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeWalletTrades) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletTrades) SetMethod(method string) {
	s.Method = method
	s.require(subscribeWalletTradesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletTrades) SetTopic(topic string) {
	s.Topic = topic
	s.require(subscribeWalletTradesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletTrades) SetParams(params *SubscribeWalletTradesParams) {
	s.Params = params
	s.require(subscribeWalletTradesFieldParams)
}

func (s *SubscribeWalletTrades) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeWalletTrades
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeWalletTrades(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeWalletTrades) MarshalJSON() ([]byte, error) {
	type embed SubscribeWalletTrades
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeWalletTrades) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeWalletTradesParamsFieldWallets = big.NewInt(1 << 0)
)

type SubscribeWalletTradesParams struct {
	Wallets []string `json:"wallets,omitempty" url:"wallets,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeWalletTradesParams) GetWallets() []string {
	if s == nil {
		return nil
	}
	return s.Wallets
}

func (s *SubscribeWalletTradesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeWalletTradesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWallets sets the Wallets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletTradesParams) SetWallets(wallets []string) {
	s.Wallets = wallets
	s.require(subscribeWalletTradesParamsFieldWallets)
}

func (s *SubscribeWalletTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeWalletTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeWalletTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeWalletTradesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeWalletTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeWalletTradesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	tokenTradesSubscriptionMessageFieldTopic = big.NewInt(1 << 0)
	tokenTradesSubscriptionMessageFieldData  = big.NewInt(1 << 1)
)

type TokenTradesSubscriptionMessage struct {
	Topic *string                             `json:"topic,omitempty" url:"topic,omitempty"`
	Data  *TokenTradesSubscriptionMessageData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenTradesSubscriptionMessage) GetTopic() *string {
	if t == nil {
		return nil
	}
	return t.Topic
}

func (t *TokenTradesSubscriptionMessage) GetData() *TokenTradesSubscriptionMessageData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TokenTradesSubscriptionMessage) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TokenTradesSubscriptionMessage) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessage) SetTopic(topic *string) {
	t.Topic = topic
	t.require(tokenTradesSubscriptionMessageFieldTopic)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessage) SetData(data *TokenTradesSubscriptionMessageData) {
	t.Data = data
	t.require(tokenTradesSubscriptionMessageFieldData)
}

func (t *TokenTradesSubscriptionMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenTradesSubscriptionMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenTradesSubscriptionMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenTradesSubscriptionMessage) MarshalJSON() ([]byte, error) {
	type embed TokenTradesSubscriptionMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TokenTradesSubscriptionMessage) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tokenTradesSubscriptionMessageDataFieldID               = big.NewInt(1 << 0)
	tokenTradesSubscriptionMessageDataFieldProtocol         = big.NewInt(1 << 1)
	tokenTradesSubscriptionMessageDataFieldSwapType         = big.NewInt(1 << 2)
	tokenTradesSubscriptionMessageDataFieldWalletAddress    = big.NewInt(1 << 3)
	tokenTradesSubscriptionMessageDataFieldTokenAddress     = big.NewInt(1 << 4)
	tokenTradesSubscriptionMessageDataFieldQuoteAddress     = big.NewInt(1 << 5)
	tokenTradesSubscriptionMessageDataFieldPositionAddress  = big.NewInt(1 << 6)
	tokenTradesSubscriptionMessageDataFieldDirection        = big.NewInt(1 << 7)
	tokenTradesSubscriptionMessageDataFieldPositionState    = big.NewInt(1 << 8)
	tokenTradesSubscriptionMessageDataFieldTokenAmount      = big.NewInt(1 << 9)
	tokenTradesSubscriptionMessageDataFieldQuoteAmount      = big.NewInt(1 << 10)
	tokenTradesSubscriptionMessageDataFieldNativeAmount     = big.NewInt(1 << 11)
	tokenTradesSubscriptionMessageDataFieldUsdAmount        = big.NewInt(1 << 12)
	tokenTradesSubscriptionMessageDataFieldPreTokenBalance  = big.NewInt(1 << 13)
	tokenTradesSubscriptionMessageDataFieldPostTokenBalance = big.NewInt(1 << 14)
	tokenTradesSubscriptionMessageDataFieldTokenPrice       = big.NewInt(1 << 15)
	tokenTradesSubscriptionMessageDataFieldQuotePrice       = big.NewInt(1 << 16)
	tokenTradesSubscriptionMessageDataFieldTokenMcap        = big.NewInt(1 << 17)
	tokenTradesSubscriptionMessageDataFieldBlockSlot        = big.NewInt(1 << 18)
	tokenTradesSubscriptionMessageDataFieldBlockTime        = big.NewInt(1 << 19)
	tokenTradesSubscriptionMessageDataFieldTxHash           = big.NewInt(1 << 20)
)

type TokenTradesSubscriptionMessageData struct {
	ID *int `json:"id,omitempty" url:"id,omitempty"`
	// Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
	Protocol         *string                                          `json:"protocol,omitempty" url:"protocol,omitempty"`
	SwapType         *TokenTradesSubscriptionMessageDataSwapType      `json:"swap_type,omitempty" url:"swap_type,omitempty"`
	WalletAddress    *string                                          `json:"wallet_address,omitempty" url:"wallet_address,omitempty"`
	TokenAddress     *string                                          `json:"token_address,omitempty" url:"token_address,omitempty"`
	QuoteAddress     *string                                          `json:"quote_address,omitempty" url:"quote_address,omitempty"`
	PositionAddress  *string                                          `json:"position_address,omitempty" url:"position_address,omitempty"`
	Direction        *TokenTradesSubscriptionMessageDataDirection     `json:"direction,omitempty" url:"direction,omitempty"`
	PositionState    *TokenTradesSubscriptionMessageDataPositionState `json:"position_state,omitempty" url:"position_state,omitempty"`
	TokenAmount      *float64                                         `json:"token_amount,omitempty" url:"token_amount,omitempty"`
	QuoteAmount      *float64                                         `json:"quote_amount,omitempty" url:"quote_amount,omitempty"`
	NativeAmount     *float64                                         `json:"native_amount,omitempty" url:"native_amount,omitempty"`
	UsdAmount        *float64                                         `json:"usd_amount,omitempty" url:"usd_amount,omitempty"`
	PreTokenBalance  *float64                                         `json:"pre_token_balance,omitempty" url:"pre_token_balance,omitempty"`
	PostTokenBalance *float64                                         `json:"post_token_balance,omitempty" url:"post_token_balance,omitempty"`
	TokenPrice       *float64                                         `json:"token_price,omitempty" url:"token_price,omitempty"`
	QuotePrice       *float64                                         `json:"quote_price,omitempty" url:"quote_price,omitempty"`
	TokenMcap        *float64                                         `json:"token_mcap,omitempty" url:"token_mcap,omitempty"`
	BlockSlot        *int                                             `json:"block_slot,omitempty" url:"block_slot,omitempty"`
	BlockTime        *time.Time                                       `json:"block_time,omitempty" url:"block_time,omitempty"`
	TxHash           *string                                          `json:"tx_hash,omitempty" url:"tx_hash,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenTradesSubscriptionMessageData) GetID() *int {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TokenTradesSubscriptionMessageData) GetProtocol() *string {
	if t == nil {
		return nil
	}
	return t.Protocol
}

func (t *TokenTradesSubscriptionMessageData) GetSwapType() *TokenTradesSubscriptionMessageDataSwapType {
	if t == nil {
		return nil
	}
	return t.SwapType
}

func (t *TokenTradesSubscriptionMessageData) GetWalletAddress() *string {
	if t == nil {
		return nil
	}
	return t.WalletAddress
}

func (t *TokenTradesSubscriptionMessageData) GetTokenAddress() *string {
	if t == nil {
		return nil
	}
	return t.TokenAddress
}

func (t *TokenTradesSubscriptionMessageData) GetQuoteAddress() *string {
	if t == nil {
		return nil
	}
	return t.QuoteAddress
}

func (t *TokenTradesSubscriptionMessageData) GetPositionAddress() *string {
	if t == nil {
		return nil
	}
	return t.PositionAddress
}

func (t *TokenTradesSubscriptionMessageData) GetDirection() *TokenTradesSubscriptionMessageDataDirection {
	if t == nil {
		return nil
	}
	return t.Direction
}

func (t *TokenTradesSubscriptionMessageData) GetPositionState() *TokenTradesSubscriptionMessageDataPositionState {
	if t == nil {
		return nil
	}
	return t.PositionState
}

func (t *TokenTradesSubscriptionMessageData) GetTokenAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenAmount
}

func (t *TokenTradesSubscriptionMessageData) GetQuoteAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.QuoteAmount
}

func (t *TokenTradesSubscriptionMessageData) GetNativeAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.NativeAmount
}

func (t *TokenTradesSubscriptionMessageData) GetUsdAmount() *float64 {
	if t == nil {
		return nil
	}
	return t.UsdAmount
}

func (t *TokenTradesSubscriptionMessageData) GetPreTokenBalance() *float64 {
	if t == nil {
		return nil
	}
	return t.PreTokenBalance
}

func (t *TokenTradesSubscriptionMessageData) GetPostTokenBalance() *float64 {
	if t == nil {
		return nil
	}
	return t.PostTokenBalance
}

func (t *TokenTradesSubscriptionMessageData) GetTokenPrice() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenPrice
}

func (t *TokenTradesSubscriptionMessageData) GetQuotePrice() *float64 {
	if t == nil {
		return nil
	}
	return t.QuotePrice
}

func (t *TokenTradesSubscriptionMessageData) GetTokenMcap() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenMcap
}

func (t *TokenTradesSubscriptionMessageData) GetBlockSlot() *int {
	if t == nil {
		return nil
	}
	return t.BlockSlot
}

func (t *TokenTradesSubscriptionMessageData) GetBlockTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.BlockTime
}

func (t *TokenTradesSubscriptionMessageData) GetTxHash() *string {
	if t == nil {
		return nil
	}
	return t.TxHash
}

func (t *TokenTradesSubscriptionMessageData) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TokenTradesSubscriptionMessageData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetID(id *int) {
	t.ID = id
	t.require(tokenTradesSubscriptionMessageDataFieldID)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetProtocol(protocol *string) {
	t.Protocol = protocol
	t.require(tokenTradesSubscriptionMessageDataFieldProtocol)
}

// SetSwapType sets the SwapType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetSwapType(swapType *TokenTradesSubscriptionMessageDataSwapType) {
	t.SwapType = swapType
	t.require(tokenTradesSubscriptionMessageDataFieldSwapType)
}

// SetWalletAddress sets the WalletAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetWalletAddress(walletAddress *string) {
	t.WalletAddress = walletAddress
	t.require(tokenTradesSubscriptionMessageDataFieldWalletAddress)
}

// SetTokenAddress sets the TokenAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetTokenAddress(tokenAddress *string) {
	t.TokenAddress = tokenAddress
	t.require(tokenTradesSubscriptionMessageDataFieldTokenAddress)
}

// SetQuoteAddress sets the QuoteAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetQuoteAddress(quoteAddress *string) {
	t.QuoteAddress = quoteAddress
	t.require(tokenTradesSubscriptionMessageDataFieldQuoteAddress)
}

// SetPositionAddress sets the PositionAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetPositionAddress(positionAddress *string) {
	t.PositionAddress = positionAddress
	t.require(tokenTradesSubscriptionMessageDataFieldPositionAddress)
}

// SetDirection sets the Direction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetDirection(direction *TokenTradesSubscriptionMessageDataDirection) {
	t.Direction = direction
	t.require(tokenTradesSubscriptionMessageDataFieldDirection)
}

// SetPositionState sets the PositionState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetPositionState(positionState *TokenTradesSubscriptionMessageDataPositionState) {
	t.PositionState = positionState
	t.require(tokenTradesSubscriptionMessageDataFieldPositionState)
}

// SetTokenAmount sets the TokenAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetTokenAmount(tokenAmount *float64) {
	t.TokenAmount = tokenAmount
	t.require(tokenTradesSubscriptionMessageDataFieldTokenAmount)
}

// SetQuoteAmount sets the QuoteAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetQuoteAmount(quoteAmount *float64) {
	t.QuoteAmount = quoteAmount
	t.require(tokenTradesSubscriptionMessageDataFieldQuoteAmount)
}

// SetNativeAmount sets the NativeAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetNativeAmount(nativeAmount *float64) {
	t.NativeAmount = nativeAmount
	t.require(tokenTradesSubscriptionMessageDataFieldNativeAmount)
}

// SetUsdAmount sets the UsdAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetUsdAmount(usdAmount *float64) {
	t.UsdAmount = usdAmount
	t.require(tokenTradesSubscriptionMessageDataFieldUsdAmount)
}

// SetPreTokenBalance sets the PreTokenBalance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetPreTokenBalance(preTokenBalance *float64) {
	t.PreTokenBalance = preTokenBalance
	t.require(tokenTradesSubscriptionMessageDataFieldPreTokenBalance)
}

// SetPostTokenBalance sets the PostTokenBalance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetPostTokenBalance(postTokenBalance *float64) {
	t.PostTokenBalance = postTokenBalance
	t.require(tokenTradesSubscriptionMessageDataFieldPostTokenBalance)
}

// SetTokenPrice sets the TokenPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetTokenPrice(tokenPrice *float64) {
	t.TokenPrice = tokenPrice
	t.require(tokenTradesSubscriptionMessageDataFieldTokenPrice)
}

// SetQuotePrice sets the QuotePrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetQuotePrice(quotePrice *float64) {
	t.QuotePrice = quotePrice
	t.require(tokenTradesSubscriptionMessageDataFieldQuotePrice)
}

// SetTokenMcap sets the TokenMcap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetTokenMcap(tokenMcap *float64) {
	t.TokenMcap = tokenMcap
	t.require(tokenTradesSubscriptionMessageDataFieldTokenMcap)
}

// SetBlockSlot sets the BlockSlot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetBlockSlot(blockSlot *int) {
	t.BlockSlot = blockSlot
	t.require(tokenTradesSubscriptionMessageDataFieldBlockSlot)
}

// SetBlockTime sets the BlockTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetBlockTime(blockTime *time.Time) {
	t.BlockTime = blockTime
	t.require(tokenTradesSubscriptionMessageDataFieldBlockTime)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenTradesSubscriptionMessageData) SetTxHash(txHash *string) {
	t.TxHash = txHash
	t.require(tokenTradesSubscriptionMessageDataFieldTxHash)
}

func (t *TokenTradesSubscriptionMessageData) UnmarshalJSON(data []byte) error {
	type embed TokenTradesSubscriptionMessageData
	var unmarshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TokenTradesSubscriptionMessageData(unmarshaler.embed)
	t.BlockTime = unmarshaler.BlockTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenTradesSubscriptionMessageData) MarshalJSON() ([]byte, error) {
	type embed TokenTradesSubscriptionMessageData
	var marshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed:     embed(*t),
		BlockTime: internal.NewOptionalDateTime(t.BlockTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TokenTradesSubscriptionMessageData) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TokenTradesSubscriptionMessageDataDirection string

const (
	TokenTradesSubscriptionMessageDataDirectionBuy  TokenTradesSubscriptionMessageDataDirection = "buy"
	TokenTradesSubscriptionMessageDataDirectionSell TokenTradesSubscriptionMessageDataDirection = "sell"
)

func NewTokenTradesSubscriptionMessageDataDirectionFromString(s string) (TokenTradesSubscriptionMessageDataDirection, error) {
	switch s {
	case "buy":
		return TokenTradesSubscriptionMessageDataDirectionBuy, nil
	case "sell":
		return TokenTradesSubscriptionMessageDataDirectionSell, nil
	}
	var t TokenTradesSubscriptionMessageDataDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenTradesSubscriptionMessageDataDirection) Ptr() *TokenTradesSubscriptionMessageDataDirection {
	return &t
}

type TokenTradesSubscriptionMessageDataPositionState string

const (
	TokenTradesSubscriptionMessageDataPositionStateOpen  TokenTradesSubscriptionMessageDataPositionState = "open"
	TokenTradesSubscriptionMessageDataPositionStateClose TokenTradesSubscriptionMessageDataPositionState = "close"
	TokenTradesSubscriptionMessageDataPositionStateTrade TokenTradesSubscriptionMessageDataPositionState = "trade"
)

func NewTokenTradesSubscriptionMessageDataPositionStateFromString(s string) (TokenTradesSubscriptionMessageDataPositionState, error) {
	switch s {
	case "open":
		return TokenTradesSubscriptionMessageDataPositionStateOpen, nil
	case "close":
		return TokenTradesSubscriptionMessageDataPositionStateClose, nil
	case "trade":
		return TokenTradesSubscriptionMessageDataPositionStateTrade, nil
	}
	var t TokenTradesSubscriptionMessageDataPositionState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenTradesSubscriptionMessageDataPositionState) Ptr() *TokenTradesSubscriptionMessageDataPositionState {
	return &t
}

type TokenTradesSubscriptionMessageDataSwapType string

const (
	TokenTradesSubscriptionMessageDataSwapTypeQuoteToken TokenTradesSubscriptionMessageDataSwapType = "quote_token"
	TokenTradesSubscriptionMessageDataSwapTypeTokenQuote TokenTradesSubscriptionMessageDataSwapType = "token_quote"
	TokenTradesSubscriptionMessageDataSwapTypeTokenToken TokenTradesSubscriptionMessageDataSwapType = "token_token"
	TokenTradesSubscriptionMessageDataSwapTypeQuoteQuote TokenTradesSubscriptionMessageDataSwapType = "quote_quote"
)

func NewTokenTradesSubscriptionMessageDataSwapTypeFromString(s string) (TokenTradesSubscriptionMessageDataSwapType, error) {
	switch s {
	case "quote_token":
		return TokenTradesSubscriptionMessageDataSwapTypeQuoteToken, nil
	case "token_quote":
		return TokenTradesSubscriptionMessageDataSwapTypeTokenQuote, nil
	case "token_token":
		return TokenTradesSubscriptionMessageDataSwapTypeTokenToken, nil
	case "quote_quote":
		return TokenTradesSubscriptionMessageDataSwapTypeQuoteQuote, nil
	}
	var t TokenTradesSubscriptionMessageDataSwapType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenTradesSubscriptionMessageDataSwapType) Ptr() *TokenTradesSubscriptionMessageDataSwapType {
	return &t
}

var (
	unsubscribeTokenTradesFieldMethod = big.NewInt(1 << 0)
	unsubscribeTokenTradesFieldTopic  = big.NewInt(1 << 1)
	unsubscribeTokenTradesFieldParams = big.NewInt(1 << 2)
)

type UnsubscribeTokenTrades struct {
	Method string                        `json:"method" url:"method"`
	Topic  string                        `json:"topic" url:"topic"`
	Params *UnsubscribeTokenTradesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeTokenTrades) GetMethod() string {
	if u == nil {
		return ""
	}
	return u.Method
}

func (u *UnsubscribeTokenTrades) GetTopic() string {
	if u == nil {
		return ""
	}
	return u.Topic
}

func (u *UnsubscribeTokenTrades) GetParams() *UnsubscribeTokenTradesParams {
	if u == nil {
		return nil
	}
	return u.Params
}

func (u *UnsubscribeTokenTrades) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeTokenTrades) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenTrades) SetMethod(method string) {
	u.Method = method
	u.require(unsubscribeTokenTradesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenTrades) SetTopic(topic string) {
	u.Topic = topic
	u.require(unsubscribeTokenTradesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenTrades) SetParams(params *UnsubscribeTokenTradesParams) {
	u.Params = params
	u.require(unsubscribeTokenTradesFieldParams)
}

func (u *UnsubscribeTokenTrades) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeTokenTrades
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeTokenTrades(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeTokenTrades) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeTokenTrades
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeTokenTrades) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeTokenTradesParamsFieldTokens = big.NewInt(1 << 0)
)

type UnsubscribeTokenTradesParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeTokenTradesParams) GetTokens() []string {
	if u == nil {
		return nil
	}
	return u.Tokens
}

func (u *UnsubscribeTokenTradesParams) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeTokenTradesParams) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenTradesParams) SetTokens(tokens []string) {
	u.Tokens = tokens
	u.require(unsubscribeTokenTradesParamsFieldTokens)
}

func (u *UnsubscribeTokenTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeTokenTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeTokenTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeTokenTradesParams) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeTokenTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeTokenTradesParams) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeWalletTradesFieldMethod = big.NewInt(1 << 0)
	unsubscribeWalletTradesFieldTopic  = big.NewInt(1 << 1)
	unsubscribeWalletTradesFieldParams = big.NewInt(1 << 2)
)

type UnsubscribeWalletTrades struct {
	Method string                         `json:"method" url:"method"`
	Topic  string                         `json:"topic" url:"topic"`
	Params *UnsubscribeWalletTradesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeWalletTrades) GetMethod() string {
	if u == nil {
		return ""
	}
	return u.Method
}

func (u *UnsubscribeWalletTrades) GetTopic() string {
	if u == nil {
		return ""
	}
	return u.Topic
}

func (u *UnsubscribeWalletTrades) GetParams() *UnsubscribeWalletTradesParams {
	if u == nil {
		return nil
	}
	return u.Params
}

func (u *UnsubscribeWalletTrades) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeWalletTrades) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletTrades) SetMethod(method string) {
	u.Method = method
	u.require(unsubscribeWalletTradesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletTrades) SetTopic(topic string) {
	u.Topic = topic
	u.require(unsubscribeWalletTradesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletTrades) SetParams(params *UnsubscribeWalletTradesParams) {
	u.Params = params
	u.require(unsubscribeWalletTradesFieldParams)
}

func (u *UnsubscribeWalletTrades) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeWalletTrades
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeWalletTrades(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeWalletTrades) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeWalletTrades
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeWalletTrades) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeWalletTradesParamsFieldWallets = big.NewInt(1 << 0)
)

type UnsubscribeWalletTradesParams struct {
	Wallets []string `json:"wallets,omitempty" url:"wallets,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeWalletTradesParams) GetWallets() []string {
	if u == nil {
		return nil
	}
	return u.Wallets
}

func (u *UnsubscribeWalletTradesParams) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeWalletTradesParams) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetWallets sets the Wallets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletTradesParams) SetWallets(wallets []string) {
	u.Wallets = wallets
	u.require(unsubscribeWalletTradesParamsFieldWallets)
}

func (u *UnsubscribeWalletTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeWalletTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeWalletTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeWalletTradesParams) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeWalletTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeWalletTradesParams) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	walletTradesSubscriptionMessageFieldTopic = big.NewInt(1 << 0)
	walletTradesSubscriptionMessageFieldData  = big.NewInt(1 << 1)
)

type WalletTradesSubscriptionMessage struct {
	Topic *string                              `json:"topic,omitempty" url:"topic,omitempty"`
	Data  *WalletTradesSubscriptionMessageData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletTradesSubscriptionMessage) GetTopic() *string {
	if w == nil {
		return nil
	}
	return w.Topic
}

func (w *WalletTradesSubscriptionMessage) GetData() *WalletTradesSubscriptionMessageData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WalletTradesSubscriptionMessage) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletTradesSubscriptionMessage) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessage) SetTopic(topic *string) {
	w.Topic = topic
	w.require(walletTradesSubscriptionMessageFieldTopic)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessage) SetData(data *WalletTradesSubscriptionMessageData) {
	w.Data = data
	w.require(walletTradesSubscriptionMessageFieldData)
}

func (w *WalletTradesSubscriptionMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler WalletTradesSubscriptionMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WalletTradesSubscriptionMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletTradesSubscriptionMessage) MarshalJSON() ([]byte, error) {
	type embed WalletTradesSubscriptionMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletTradesSubscriptionMessage) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletTradesSubscriptionMessageDataFieldID               = big.NewInt(1 << 0)
	walletTradesSubscriptionMessageDataFieldProtocol         = big.NewInt(1 << 1)
	walletTradesSubscriptionMessageDataFieldSwapType         = big.NewInt(1 << 2)
	walletTradesSubscriptionMessageDataFieldWalletAddress    = big.NewInt(1 << 3)
	walletTradesSubscriptionMessageDataFieldTokenAddress     = big.NewInt(1 << 4)
	walletTradesSubscriptionMessageDataFieldQuoteAddress     = big.NewInt(1 << 5)
	walletTradesSubscriptionMessageDataFieldPositionAddress  = big.NewInt(1 << 6)
	walletTradesSubscriptionMessageDataFieldDirection        = big.NewInt(1 << 7)
	walletTradesSubscriptionMessageDataFieldPositionState    = big.NewInt(1 << 8)
	walletTradesSubscriptionMessageDataFieldTokenAmount      = big.NewInt(1 << 9)
	walletTradesSubscriptionMessageDataFieldQuoteAmount      = big.NewInt(1 << 10)
	walletTradesSubscriptionMessageDataFieldNativeAmount     = big.NewInt(1 << 11)
	walletTradesSubscriptionMessageDataFieldUsdAmount        = big.NewInt(1 << 12)
	walletTradesSubscriptionMessageDataFieldPreTokenBalance  = big.NewInt(1 << 13)
	walletTradesSubscriptionMessageDataFieldPostTokenBalance = big.NewInt(1 << 14)
	walletTradesSubscriptionMessageDataFieldTokenPrice       = big.NewInt(1 << 15)
	walletTradesSubscriptionMessageDataFieldQuotePrice       = big.NewInt(1 << 16)
	walletTradesSubscriptionMessageDataFieldTokenMcap        = big.NewInt(1 << 17)
	walletTradesSubscriptionMessageDataFieldBlockSlot        = big.NewInt(1 << 18)
	walletTradesSubscriptionMessageDataFieldBlockTime        = big.NewInt(1 << 19)
	walletTradesSubscriptionMessageDataFieldTxHash           = big.NewInt(1 << 20)
)

type WalletTradesSubscriptionMessageData struct {
	ID *int `json:"id,omitempty" url:"id,omitempty"`
	// Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
	Protocol         *string                                           `json:"protocol,omitempty" url:"protocol,omitempty"`
	SwapType         *WalletTradesSubscriptionMessageDataSwapType      `json:"swap_type,omitempty" url:"swap_type,omitempty"`
	WalletAddress    *string                                           `json:"wallet_address,omitempty" url:"wallet_address,omitempty"`
	TokenAddress     *string                                           `json:"token_address,omitempty" url:"token_address,omitempty"`
	QuoteAddress     *string                                           `json:"quote_address,omitempty" url:"quote_address,omitempty"`
	PositionAddress  *string                                           `json:"position_address,omitempty" url:"position_address,omitempty"`
	Direction        *WalletTradesSubscriptionMessageDataDirection     `json:"direction,omitempty" url:"direction,omitempty"`
	PositionState    *WalletTradesSubscriptionMessageDataPositionState `json:"position_state,omitempty" url:"position_state,omitempty"`
	TokenAmount      *float64                                          `json:"token_amount,omitempty" url:"token_amount,omitempty"`
	QuoteAmount      *float64                                          `json:"quote_amount,omitempty" url:"quote_amount,omitempty"`
	NativeAmount     *float64                                          `json:"native_amount,omitempty" url:"native_amount,omitempty"`
	UsdAmount        *float64                                          `json:"usd_amount,omitempty" url:"usd_amount,omitempty"`
	PreTokenBalance  *float64                                          `json:"pre_token_balance,omitempty" url:"pre_token_balance,omitempty"`
	PostTokenBalance *float64                                          `json:"post_token_balance,omitempty" url:"post_token_balance,omitempty"`
	TokenPrice       *float64                                          `json:"token_price,omitempty" url:"token_price,omitempty"`
	QuotePrice       *float64                                          `json:"quote_price,omitempty" url:"quote_price,omitempty"`
	TokenMcap        *float64                                          `json:"token_mcap,omitempty" url:"token_mcap,omitempty"`
	BlockSlot        *int                                              `json:"block_slot,omitempty" url:"block_slot,omitempty"`
	BlockTime        *time.Time                                        `json:"block_time,omitempty" url:"block_time,omitempty"`
	TxHash           *string                                           `json:"tx_hash,omitempty" url:"tx_hash,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletTradesSubscriptionMessageData) GetID() *int {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WalletTradesSubscriptionMessageData) GetProtocol() *string {
	if w == nil {
		return nil
	}
	return w.Protocol
}

func (w *WalletTradesSubscriptionMessageData) GetSwapType() *WalletTradesSubscriptionMessageDataSwapType {
	if w == nil {
		return nil
	}
	return w.SwapType
}

func (w *WalletTradesSubscriptionMessageData) GetWalletAddress() *string {
	if w == nil {
		return nil
	}
	return w.WalletAddress
}

func (w *WalletTradesSubscriptionMessageData) GetTokenAddress() *string {
	if w == nil {
		return nil
	}
	return w.TokenAddress
}

func (w *WalletTradesSubscriptionMessageData) GetQuoteAddress() *string {
	if w == nil {
		return nil
	}
	return w.QuoteAddress
}

func (w *WalletTradesSubscriptionMessageData) GetPositionAddress() *string {
	if w == nil {
		return nil
	}
	return w.PositionAddress
}

func (w *WalletTradesSubscriptionMessageData) GetDirection() *WalletTradesSubscriptionMessageDataDirection {
	if w == nil {
		return nil
	}
	return w.Direction
}

func (w *WalletTradesSubscriptionMessageData) GetPositionState() *WalletTradesSubscriptionMessageDataPositionState {
	if w == nil {
		return nil
	}
	return w.PositionState
}

func (w *WalletTradesSubscriptionMessageData) GetTokenAmount() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenAmount
}

func (w *WalletTradesSubscriptionMessageData) GetQuoteAmount() *float64 {
	if w == nil {
		return nil
	}
	return w.QuoteAmount
}

func (w *WalletTradesSubscriptionMessageData) GetNativeAmount() *float64 {
	if w == nil {
		return nil
	}
	return w.NativeAmount
}

func (w *WalletTradesSubscriptionMessageData) GetUsdAmount() *float64 {
	if w == nil {
		return nil
	}
	return w.UsdAmount
}

func (w *WalletTradesSubscriptionMessageData) GetPreTokenBalance() *float64 {
	if w == nil {
		return nil
	}
	return w.PreTokenBalance
}

func (w *WalletTradesSubscriptionMessageData) GetPostTokenBalance() *float64 {
	if w == nil {
		return nil
	}
	return w.PostTokenBalance
}

func (w *WalletTradesSubscriptionMessageData) GetTokenPrice() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenPrice
}

func (w *WalletTradesSubscriptionMessageData) GetQuotePrice() *float64 {
	if w == nil {
		return nil
	}
	return w.QuotePrice
}

func (w *WalletTradesSubscriptionMessageData) GetTokenMcap() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenMcap
}

func (w *WalletTradesSubscriptionMessageData) GetBlockSlot() *int {
	if w == nil {
		return nil
	}
	return w.BlockSlot
}

func (w *WalletTradesSubscriptionMessageData) GetBlockTime() *time.Time {
	if w == nil {
		return nil
	}
	return w.BlockTime
}

func (w *WalletTradesSubscriptionMessageData) GetTxHash() *string {
	if w == nil {
		return nil
	}
	return w.TxHash
}

func (w *WalletTradesSubscriptionMessageData) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletTradesSubscriptionMessageData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetID(id *int) {
	w.ID = id
	w.require(walletTradesSubscriptionMessageDataFieldID)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetProtocol(protocol *string) {
	w.Protocol = protocol
	w.require(walletTradesSubscriptionMessageDataFieldProtocol)
}

// SetSwapType sets the SwapType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetSwapType(swapType *WalletTradesSubscriptionMessageDataSwapType) {
	w.SwapType = swapType
	w.require(walletTradesSubscriptionMessageDataFieldSwapType)
}

// SetWalletAddress sets the WalletAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetWalletAddress(walletAddress *string) {
	w.WalletAddress = walletAddress
	w.require(walletTradesSubscriptionMessageDataFieldWalletAddress)
}

// SetTokenAddress sets the TokenAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetTokenAddress(tokenAddress *string) {
	w.TokenAddress = tokenAddress
	w.require(walletTradesSubscriptionMessageDataFieldTokenAddress)
}

// SetQuoteAddress sets the QuoteAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetQuoteAddress(quoteAddress *string) {
	w.QuoteAddress = quoteAddress
	w.require(walletTradesSubscriptionMessageDataFieldQuoteAddress)
}

// SetPositionAddress sets the PositionAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetPositionAddress(positionAddress *string) {
	w.PositionAddress = positionAddress
	w.require(walletTradesSubscriptionMessageDataFieldPositionAddress)
}

// SetDirection sets the Direction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetDirection(direction *WalletTradesSubscriptionMessageDataDirection) {
	w.Direction = direction
	w.require(walletTradesSubscriptionMessageDataFieldDirection)
}

// SetPositionState sets the PositionState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetPositionState(positionState *WalletTradesSubscriptionMessageDataPositionState) {
	w.PositionState = positionState
	w.require(walletTradesSubscriptionMessageDataFieldPositionState)
}

// SetTokenAmount sets the TokenAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetTokenAmount(tokenAmount *float64) {
	w.TokenAmount = tokenAmount
	w.require(walletTradesSubscriptionMessageDataFieldTokenAmount)
}

// SetQuoteAmount sets the QuoteAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetQuoteAmount(quoteAmount *float64) {
	w.QuoteAmount = quoteAmount
	w.require(walletTradesSubscriptionMessageDataFieldQuoteAmount)
}

// SetNativeAmount sets the NativeAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetNativeAmount(nativeAmount *float64) {
	w.NativeAmount = nativeAmount
	w.require(walletTradesSubscriptionMessageDataFieldNativeAmount)
}

// SetUsdAmount sets the UsdAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetUsdAmount(usdAmount *float64) {
	w.UsdAmount = usdAmount
	w.require(walletTradesSubscriptionMessageDataFieldUsdAmount)
}

// SetPreTokenBalance sets the PreTokenBalance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetPreTokenBalance(preTokenBalance *float64) {
	w.PreTokenBalance = preTokenBalance
	w.require(walletTradesSubscriptionMessageDataFieldPreTokenBalance)
}

// SetPostTokenBalance sets the PostTokenBalance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetPostTokenBalance(postTokenBalance *float64) {
	w.PostTokenBalance = postTokenBalance
	w.require(walletTradesSubscriptionMessageDataFieldPostTokenBalance)
}

// SetTokenPrice sets the TokenPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetTokenPrice(tokenPrice *float64) {
	w.TokenPrice = tokenPrice
	w.require(walletTradesSubscriptionMessageDataFieldTokenPrice)
}

// SetQuotePrice sets the QuotePrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetQuotePrice(quotePrice *float64) {
	w.QuotePrice = quotePrice
	w.require(walletTradesSubscriptionMessageDataFieldQuotePrice)
}

// SetTokenMcap sets the TokenMcap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetTokenMcap(tokenMcap *float64) {
	w.TokenMcap = tokenMcap
	w.require(walletTradesSubscriptionMessageDataFieldTokenMcap)
}

// SetBlockSlot sets the BlockSlot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetBlockSlot(blockSlot *int) {
	w.BlockSlot = blockSlot
	w.require(walletTradesSubscriptionMessageDataFieldBlockSlot)
}

// SetBlockTime sets the BlockTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetBlockTime(blockTime *time.Time) {
	w.BlockTime = blockTime
	w.require(walletTradesSubscriptionMessageDataFieldBlockTime)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTradesSubscriptionMessageData) SetTxHash(txHash *string) {
	w.TxHash = txHash
	w.require(walletTradesSubscriptionMessageDataFieldTxHash)
}

func (w *WalletTradesSubscriptionMessageData) UnmarshalJSON(data []byte) error {
	type embed WalletTradesSubscriptionMessageData
	var unmarshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletTradesSubscriptionMessageData(unmarshaler.embed)
	w.BlockTime = unmarshaler.BlockTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletTradesSubscriptionMessageData) MarshalJSON() ([]byte, error) {
	type embed WalletTradesSubscriptionMessageData
	var marshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed:     embed(*w),
		BlockTime: internal.NewOptionalDateTime(w.BlockTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletTradesSubscriptionMessageData) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WalletTradesSubscriptionMessageDataDirection string

const (
	WalletTradesSubscriptionMessageDataDirectionBuy  WalletTradesSubscriptionMessageDataDirection = "buy"
	WalletTradesSubscriptionMessageDataDirectionSell WalletTradesSubscriptionMessageDataDirection = "sell"
)

func NewWalletTradesSubscriptionMessageDataDirectionFromString(s string) (WalletTradesSubscriptionMessageDataDirection, error) {
	switch s {
	case "buy":
		return WalletTradesSubscriptionMessageDataDirectionBuy, nil
	case "sell":
		return WalletTradesSubscriptionMessageDataDirectionSell, nil
	}
	var t WalletTradesSubscriptionMessageDataDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WalletTradesSubscriptionMessageDataDirection) Ptr() *WalletTradesSubscriptionMessageDataDirection {
	return &w
}

type WalletTradesSubscriptionMessageDataPositionState string

const (
	WalletTradesSubscriptionMessageDataPositionStateOpen  WalletTradesSubscriptionMessageDataPositionState = "open"
	WalletTradesSubscriptionMessageDataPositionStateClose WalletTradesSubscriptionMessageDataPositionState = "close"
	WalletTradesSubscriptionMessageDataPositionStateTrade WalletTradesSubscriptionMessageDataPositionState = "trade"
)

func NewWalletTradesSubscriptionMessageDataPositionStateFromString(s string) (WalletTradesSubscriptionMessageDataPositionState, error) {
	switch s {
	case "open":
		return WalletTradesSubscriptionMessageDataPositionStateOpen, nil
	case "close":
		return WalletTradesSubscriptionMessageDataPositionStateClose, nil
	case "trade":
		return WalletTradesSubscriptionMessageDataPositionStateTrade, nil
	}
	var t WalletTradesSubscriptionMessageDataPositionState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WalletTradesSubscriptionMessageDataPositionState) Ptr() *WalletTradesSubscriptionMessageDataPositionState {
	return &w
}

type WalletTradesSubscriptionMessageDataSwapType string

const (
	WalletTradesSubscriptionMessageDataSwapTypeQuoteToken WalletTradesSubscriptionMessageDataSwapType = "quote_token"
	WalletTradesSubscriptionMessageDataSwapTypeTokenQuote WalletTradesSubscriptionMessageDataSwapType = "token_quote"
	WalletTradesSubscriptionMessageDataSwapTypeTokenToken WalletTradesSubscriptionMessageDataSwapType = "token_token"
	WalletTradesSubscriptionMessageDataSwapTypeQuoteQuote WalletTradesSubscriptionMessageDataSwapType = "quote_quote"
)

func NewWalletTradesSubscriptionMessageDataSwapTypeFromString(s string) (WalletTradesSubscriptionMessageDataSwapType, error) {
	switch s {
	case "quote_token":
		return WalletTradesSubscriptionMessageDataSwapTypeQuoteToken, nil
	case "token_quote":
		return WalletTradesSubscriptionMessageDataSwapTypeTokenQuote, nil
	case "token_token":
		return WalletTradesSubscriptionMessageDataSwapTypeTokenToken, nil
	case "quote_quote":
		return WalletTradesSubscriptionMessageDataSwapTypeQuoteQuote, nil
	}
	var t WalletTradesSubscriptionMessageDataSwapType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WalletTradesSubscriptionMessageDataSwapType) Ptr() *WalletTradesSubscriptionMessageDataSwapType {
	return &w
}
