// Code generated by Fern. DO NOT EDIT.

package prism

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	subscribeTokenSwapsFieldMethod = big.NewInt(1 << 0)
	subscribeTokenSwapsFieldTopic  = big.NewInt(1 << 1)
	subscribeTokenSwapsFieldParams = big.NewInt(1 << 2)
)

type SubscribeTokenSwaps struct {
	Method string                     `json:"method" url:"method"`
	Topic  string                     `json:"topic" url:"topic"`
	Params *SubscribeTokenSwapsParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeTokenSwaps) GetMethod() string {
	if s == nil {
		return ""
	}
	return s.Method
}

func (s *SubscribeTokenSwaps) GetTopic() string {
	if s == nil {
		return ""
	}
	return s.Topic
}

func (s *SubscribeTokenSwaps) GetParams() *SubscribeTokenSwapsParams {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SubscribeTokenSwaps) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeTokenSwaps) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenSwaps) SetMethod(method string) {
	s.Method = method
	s.require(subscribeTokenSwapsFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenSwaps) SetTopic(topic string) {
	s.Topic = topic
	s.require(subscribeTokenSwapsFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenSwaps) SetParams(params *SubscribeTokenSwapsParams) {
	s.Params = params
	s.require(subscribeTokenSwapsFieldParams)
}

func (s *SubscribeTokenSwaps) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeTokenSwaps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeTokenSwaps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeTokenSwaps) MarshalJSON() ([]byte, error) {
	type embed SubscribeTokenSwaps
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeTokenSwaps) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeTokenSwapsParamsFieldTokens = big.NewInt(1 << 0)
)

type SubscribeTokenSwapsParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeTokenSwapsParams) GetTokens() []string {
	if s == nil {
		return nil
	}
	return s.Tokens
}

func (s *SubscribeTokenSwapsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeTokenSwapsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeTokenSwapsParams) SetTokens(tokens []string) {
	s.Tokens = tokens
	s.require(subscribeTokenSwapsParamsFieldTokens)
}

func (s *SubscribeTokenSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeTokenSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeTokenSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeTokenSwapsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeTokenSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeTokenSwapsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeWalletSwapsFieldMethod = big.NewInt(1 << 0)
	subscribeWalletSwapsFieldTopic  = big.NewInt(1 << 1)
	subscribeWalletSwapsFieldParams = big.NewInt(1 << 2)
)

type SubscribeWalletSwaps struct {
	Method string                      `json:"method" url:"method"`
	Topic  string                      `json:"topic" url:"topic"`
	Params *SubscribeWalletSwapsParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeWalletSwaps) GetMethod() string {
	if s == nil {
		return ""
	}
	return s.Method
}

func (s *SubscribeWalletSwaps) GetTopic() string {
	if s == nil {
		return ""
	}
	return s.Topic
}

func (s *SubscribeWalletSwaps) GetParams() *SubscribeWalletSwapsParams {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SubscribeWalletSwaps) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeWalletSwaps) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletSwaps) SetMethod(method string) {
	s.Method = method
	s.require(subscribeWalletSwapsFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletSwaps) SetTopic(topic string) {
	s.Topic = topic
	s.require(subscribeWalletSwapsFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletSwaps) SetParams(params *SubscribeWalletSwapsParams) {
	s.Params = params
	s.require(subscribeWalletSwapsFieldParams)
}

func (s *SubscribeWalletSwaps) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeWalletSwaps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeWalletSwaps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeWalletSwaps) MarshalJSON() ([]byte, error) {
	type embed SubscribeWalletSwaps
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeWalletSwaps) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeWalletSwapsParamsFieldWallets = big.NewInt(1 << 0)
)

type SubscribeWalletSwapsParams struct {
	Wallets []string `json:"wallets,omitempty" url:"wallets,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeWalletSwapsParams) GetWallets() []string {
	if s == nil {
		return nil
	}
	return s.Wallets
}

func (s *SubscribeWalletSwapsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeWalletSwapsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWallets sets the Wallets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeWalletSwapsParams) SetWallets(wallets []string) {
	s.Wallets = wallets
	s.require(subscribeWalletSwapsParamsFieldWallets)
}

func (s *SubscribeWalletSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeWalletSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeWalletSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeWalletSwapsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeWalletSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeWalletSwapsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	tokenSwapsSubscriptionMessageFieldTopic = big.NewInt(1 << 0)
	tokenSwapsSubscriptionMessageFieldData  = big.NewInt(1 << 1)
)

type TokenSwapsSubscriptionMessage struct {
	Topic *string                            `json:"topic,omitempty" url:"topic,omitempty"`
	Data  *TokenSwapsSubscriptionMessageData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenSwapsSubscriptionMessage) GetTopic() *string {
	if t == nil {
		return nil
	}
	return t.Topic
}

func (t *TokenSwapsSubscriptionMessage) GetData() *TokenSwapsSubscriptionMessageData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TokenSwapsSubscriptionMessage) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TokenSwapsSubscriptionMessage) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessage) SetTopic(topic *string) {
	t.Topic = topic
	t.require(tokenSwapsSubscriptionMessageFieldTopic)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessage) SetData(data *TokenSwapsSubscriptionMessageData) {
	t.Data = data
	t.require(tokenSwapsSubscriptionMessageFieldData)
}

func (t *TokenSwapsSubscriptionMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenSwapsSubscriptionMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenSwapsSubscriptionMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenSwapsSubscriptionMessage) MarshalJSON() ([]byte, error) {
	type embed TokenSwapsSubscriptionMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TokenSwapsSubscriptionMessage) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tokenSwapsSubscriptionMessageDataFieldID                  = big.NewInt(1 << 0)
	tokenSwapsSubscriptionMessageDataFieldSwapType            = big.NewInt(1 << 1)
	tokenSwapsSubscriptionMessageDataFieldProtocol            = big.NewInt(1 << 2)
	tokenSwapsSubscriptionMessageDataFieldWalletAddress       = big.NewInt(1 << 3)
	tokenSwapsSubscriptionMessageDataFieldTokenAddressIn      = big.NewInt(1 << 4)
	tokenSwapsSubscriptionMessageDataFieldTokenAddressOut     = big.NewInt(1 << 5)
	tokenSwapsSubscriptionMessageDataFieldTokenAmountIn       = big.NewInt(1 << 6)
	tokenSwapsSubscriptionMessageDataFieldTokenAmountOut      = big.NewInt(1 << 7)
	tokenSwapsSubscriptionMessageDataFieldTokenPriceIn        = big.NewInt(1 << 8)
	tokenSwapsSubscriptionMessageDataFieldTokenPriceOut       = big.NewInt(1 << 9)
	tokenSwapsSubscriptionMessageDataFieldPreTokenBalanceIn   = big.NewInt(1 << 10)
	tokenSwapsSubscriptionMessageDataFieldPreTokenBalanceOut  = big.NewInt(1 << 11)
	tokenSwapsSubscriptionMessageDataFieldPostTokenBalanceIn  = big.NewInt(1 << 12)
	tokenSwapsSubscriptionMessageDataFieldPostTokenBalanceOut = big.NewInt(1 << 13)
	tokenSwapsSubscriptionMessageDataFieldUsdAmountIn         = big.NewInt(1 << 14)
	tokenSwapsSubscriptionMessageDataFieldUsdAmountOut        = big.NewInt(1 << 15)
	tokenSwapsSubscriptionMessageDataFieldBlockSlot           = big.NewInt(1 << 16)
	tokenSwapsSubscriptionMessageDataFieldBlockTime           = big.NewInt(1 << 17)
	tokenSwapsSubscriptionMessageDataFieldTxHash              = big.NewInt(1 << 18)
)

type TokenSwapsSubscriptionMessageData struct {
	ID       *int                                       `json:"id,omitempty" url:"id,omitempty"`
	SwapType *TokenSwapsSubscriptionMessageDataSwapType `json:"swap_type,omitempty" url:"swap_type,omitempty"`
	// Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
	Protocol            *string    `json:"protocol,omitempty" url:"protocol,omitempty"`
	WalletAddress       *string    `json:"wallet_address,omitempty" url:"wallet_address,omitempty"`
	TokenAddressIn      *string    `json:"token_address_in,omitempty" url:"token_address_in,omitempty"`
	TokenAddressOut     *string    `json:"token_address_out,omitempty" url:"token_address_out,omitempty"`
	TokenAmountIn       *float64   `json:"token_amount_in,omitempty" url:"token_amount_in,omitempty"`
	TokenAmountOut      *float64   `json:"token_amount_out,omitempty" url:"token_amount_out,omitempty"`
	TokenPriceIn        *float64   `json:"token_price_in,omitempty" url:"token_price_in,omitempty"`
	TokenPriceOut       *float64   `json:"token_price_out,omitempty" url:"token_price_out,omitempty"`
	PreTokenBalanceIn   *float64   `json:"pre_token_balance_in,omitempty" url:"pre_token_balance_in,omitempty"`
	PreTokenBalanceOut  *float64   `json:"pre_token_balance_out,omitempty" url:"pre_token_balance_out,omitempty"`
	PostTokenBalanceIn  *float64   `json:"post_token_balance_in,omitempty" url:"post_token_balance_in,omitempty"`
	PostTokenBalanceOut *float64   `json:"post_token_balance_out,omitempty" url:"post_token_balance_out,omitempty"`
	UsdAmountIn         *float64   `json:"usd_amount_in,omitempty" url:"usd_amount_in,omitempty"`
	UsdAmountOut        *float64   `json:"usd_amount_out,omitempty" url:"usd_amount_out,omitempty"`
	BlockSlot           *int       `json:"block_slot,omitempty" url:"block_slot,omitempty"`
	BlockTime           *time.Time `json:"block_time,omitempty" url:"block_time,omitempty"`
	TxHash              *string    `json:"tx_hash,omitempty" url:"tx_hash,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenSwapsSubscriptionMessageData) GetID() *int {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TokenSwapsSubscriptionMessageData) GetSwapType() *TokenSwapsSubscriptionMessageDataSwapType {
	if t == nil {
		return nil
	}
	return t.SwapType
}

func (t *TokenSwapsSubscriptionMessageData) GetProtocol() *string {
	if t == nil {
		return nil
	}
	return t.Protocol
}

func (t *TokenSwapsSubscriptionMessageData) GetWalletAddress() *string {
	if t == nil {
		return nil
	}
	return t.WalletAddress
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenAddressIn() *string {
	if t == nil {
		return nil
	}
	return t.TokenAddressIn
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenAddressOut() *string {
	if t == nil {
		return nil
	}
	return t.TokenAddressOut
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenAmountIn() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenAmountIn
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenAmountOut() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenAmountOut
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenPriceIn() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenPriceIn
}

func (t *TokenSwapsSubscriptionMessageData) GetTokenPriceOut() *float64 {
	if t == nil {
		return nil
	}
	return t.TokenPriceOut
}

func (t *TokenSwapsSubscriptionMessageData) GetPreTokenBalanceIn() *float64 {
	if t == nil {
		return nil
	}
	return t.PreTokenBalanceIn
}

func (t *TokenSwapsSubscriptionMessageData) GetPreTokenBalanceOut() *float64 {
	if t == nil {
		return nil
	}
	return t.PreTokenBalanceOut
}

func (t *TokenSwapsSubscriptionMessageData) GetPostTokenBalanceIn() *float64 {
	if t == nil {
		return nil
	}
	return t.PostTokenBalanceIn
}

func (t *TokenSwapsSubscriptionMessageData) GetPostTokenBalanceOut() *float64 {
	if t == nil {
		return nil
	}
	return t.PostTokenBalanceOut
}

func (t *TokenSwapsSubscriptionMessageData) GetUsdAmountIn() *float64 {
	if t == nil {
		return nil
	}
	return t.UsdAmountIn
}

func (t *TokenSwapsSubscriptionMessageData) GetUsdAmountOut() *float64 {
	if t == nil {
		return nil
	}
	return t.UsdAmountOut
}

func (t *TokenSwapsSubscriptionMessageData) GetBlockSlot() *int {
	if t == nil {
		return nil
	}
	return t.BlockSlot
}

func (t *TokenSwapsSubscriptionMessageData) GetBlockTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.BlockTime
}

func (t *TokenSwapsSubscriptionMessageData) GetTxHash() *string {
	if t == nil {
		return nil
	}
	return t.TxHash
}

func (t *TokenSwapsSubscriptionMessageData) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TokenSwapsSubscriptionMessageData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetID(id *int) {
	t.ID = id
	t.require(tokenSwapsSubscriptionMessageDataFieldID)
}

// SetSwapType sets the SwapType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetSwapType(swapType *TokenSwapsSubscriptionMessageDataSwapType) {
	t.SwapType = swapType
	t.require(tokenSwapsSubscriptionMessageDataFieldSwapType)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetProtocol(protocol *string) {
	t.Protocol = protocol
	t.require(tokenSwapsSubscriptionMessageDataFieldProtocol)
}

// SetWalletAddress sets the WalletAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetWalletAddress(walletAddress *string) {
	t.WalletAddress = walletAddress
	t.require(tokenSwapsSubscriptionMessageDataFieldWalletAddress)
}

// SetTokenAddressIn sets the TokenAddressIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenAddressIn(tokenAddressIn *string) {
	t.TokenAddressIn = tokenAddressIn
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenAddressIn)
}

// SetTokenAddressOut sets the TokenAddressOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenAddressOut(tokenAddressOut *string) {
	t.TokenAddressOut = tokenAddressOut
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenAddressOut)
}

// SetTokenAmountIn sets the TokenAmountIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenAmountIn(tokenAmountIn *float64) {
	t.TokenAmountIn = tokenAmountIn
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenAmountIn)
}

// SetTokenAmountOut sets the TokenAmountOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenAmountOut(tokenAmountOut *float64) {
	t.TokenAmountOut = tokenAmountOut
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenAmountOut)
}

// SetTokenPriceIn sets the TokenPriceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenPriceIn(tokenPriceIn *float64) {
	t.TokenPriceIn = tokenPriceIn
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenPriceIn)
}

// SetTokenPriceOut sets the TokenPriceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTokenPriceOut(tokenPriceOut *float64) {
	t.TokenPriceOut = tokenPriceOut
	t.require(tokenSwapsSubscriptionMessageDataFieldTokenPriceOut)
}

// SetPreTokenBalanceIn sets the PreTokenBalanceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetPreTokenBalanceIn(preTokenBalanceIn *float64) {
	t.PreTokenBalanceIn = preTokenBalanceIn
	t.require(tokenSwapsSubscriptionMessageDataFieldPreTokenBalanceIn)
}

// SetPreTokenBalanceOut sets the PreTokenBalanceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetPreTokenBalanceOut(preTokenBalanceOut *float64) {
	t.PreTokenBalanceOut = preTokenBalanceOut
	t.require(tokenSwapsSubscriptionMessageDataFieldPreTokenBalanceOut)
}

// SetPostTokenBalanceIn sets the PostTokenBalanceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetPostTokenBalanceIn(postTokenBalanceIn *float64) {
	t.PostTokenBalanceIn = postTokenBalanceIn
	t.require(tokenSwapsSubscriptionMessageDataFieldPostTokenBalanceIn)
}

// SetPostTokenBalanceOut sets the PostTokenBalanceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetPostTokenBalanceOut(postTokenBalanceOut *float64) {
	t.PostTokenBalanceOut = postTokenBalanceOut
	t.require(tokenSwapsSubscriptionMessageDataFieldPostTokenBalanceOut)
}

// SetUsdAmountIn sets the UsdAmountIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetUsdAmountIn(usdAmountIn *float64) {
	t.UsdAmountIn = usdAmountIn
	t.require(tokenSwapsSubscriptionMessageDataFieldUsdAmountIn)
}

// SetUsdAmountOut sets the UsdAmountOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetUsdAmountOut(usdAmountOut *float64) {
	t.UsdAmountOut = usdAmountOut
	t.require(tokenSwapsSubscriptionMessageDataFieldUsdAmountOut)
}

// SetBlockSlot sets the BlockSlot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetBlockSlot(blockSlot *int) {
	t.BlockSlot = blockSlot
	t.require(tokenSwapsSubscriptionMessageDataFieldBlockSlot)
}

// SetBlockTime sets the BlockTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetBlockTime(blockTime *time.Time) {
	t.BlockTime = blockTime
	t.require(tokenSwapsSubscriptionMessageDataFieldBlockTime)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenSwapsSubscriptionMessageData) SetTxHash(txHash *string) {
	t.TxHash = txHash
	t.require(tokenSwapsSubscriptionMessageDataFieldTxHash)
}

func (t *TokenSwapsSubscriptionMessageData) UnmarshalJSON(data []byte) error {
	type embed TokenSwapsSubscriptionMessageData
	var unmarshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TokenSwapsSubscriptionMessageData(unmarshaler.embed)
	t.BlockTime = unmarshaler.BlockTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenSwapsSubscriptionMessageData) MarshalJSON() ([]byte, error) {
	type embed TokenSwapsSubscriptionMessageData
	var marshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed:     embed(*t),
		BlockTime: internal.NewOptionalDateTime(t.BlockTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TokenSwapsSubscriptionMessageData) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TokenSwapsSubscriptionMessageDataSwapType string

const (
	TokenSwapsSubscriptionMessageDataSwapTypeQuoteToken TokenSwapsSubscriptionMessageDataSwapType = "quote_token"
	TokenSwapsSubscriptionMessageDataSwapTypeTokenQuote TokenSwapsSubscriptionMessageDataSwapType = "token_quote"
	TokenSwapsSubscriptionMessageDataSwapTypeTokenToken TokenSwapsSubscriptionMessageDataSwapType = "token_token"
	TokenSwapsSubscriptionMessageDataSwapTypeQuoteQuote TokenSwapsSubscriptionMessageDataSwapType = "quote_quote"
)

func NewTokenSwapsSubscriptionMessageDataSwapTypeFromString(s string) (TokenSwapsSubscriptionMessageDataSwapType, error) {
	switch s {
	case "quote_token":
		return TokenSwapsSubscriptionMessageDataSwapTypeQuoteToken, nil
	case "token_quote":
		return TokenSwapsSubscriptionMessageDataSwapTypeTokenQuote, nil
	case "token_token":
		return TokenSwapsSubscriptionMessageDataSwapTypeTokenToken, nil
	case "quote_quote":
		return TokenSwapsSubscriptionMessageDataSwapTypeQuoteQuote, nil
	}
	var t TokenSwapsSubscriptionMessageDataSwapType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TokenSwapsSubscriptionMessageDataSwapType) Ptr() *TokenSwapsSubscriptionMessageDataSwapType {
	return &t
}

var (
	unsubscribeTokenSwapsFieldMethod = big.NewInt(1 << 0)
	unsubscribeTokenSwapsFieldTopic  = big.NewInt(1 << 1)
	unsubscribeTokenSwapsFieldParams = big.NewInt(1 << 2)
)

type UnsubscribeTokenSwaps struct {
	Method string                       `json:"method" url:"method"`
	Topic  string                       `json:"topic" url:"topic"`
	Params *UnsubscribeTokenSwapsParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeTokenSwaps) GetMethod() string {
	if u == nil {
		return ""
	}
	return u.Method
}

func (u *UnsubscribeTokenSwaps) GetTopic() string {
	if u == nil {
		return ""
	}
	return u.Topic
}

func (u *UnsubscribeTokenSwaps) GetParams() *UnsubscribeTokenSwapsParams {
	if u == nil {
		return nil
	}
	return u.Params
}

func (u *UnsubscribeTokenSwaps) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeTokenSwaps) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenSwaps) SetMethod(method string) {
	u.Method = method
	u.require(unsubscribeTokenSwapsFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenSwaps) SetTopic(topic string) {
	u.Topic = topic
	u.require(unsubscribeTokenSwapsFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenSwaps) SetParams(params *UnsubscribeTokenSwapsParams) {
	u.Params = params
	u.require(unsubscribeTokenSwapsFieldParams)
}

func (u *UnsubscribeTokenSwaps) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeTokenSwaps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeTokenSwaps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeTokenSwaps) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeTokenSwaps
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeTokenSwaps) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeTokenSwapsParamsFieldTokens = big.NewInt(1 << 0)
)

type UnsubscribeTokenSwapsParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeTokenSwapsParams) GetTokens() []string {
	if u == nil {
		return nil
	}
	return u.Tokens
}

func (u *UnsubscribeTokenSwapsParams) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeTokenSwapsParams) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeTokenSwapsParams) SetTokens(tokens []string) {
	u.Tokens = tokens
	u.require(unsubscribeTokenSwapsParamsFieldTokens)
}

func (u *UnsubscribeTokenSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeTokenSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeTokenSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeTokenSwapsParams) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeTokenSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeTokenSwapsParams) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeWalletSwapsFieldMethod = big.NewInt(1 << 0)
	unsubscribeWalletSwapsFieldTopic  = big.NewInt(1 << 1)
	unsubscribeWalletSwapsFieldParams = big.NewInt(1 << 2)
)

type UnsubscribeWalletSwaps struct {
	Method string                        `json:"method" url:"method"`
	Topic  string                        `json:"topic" url:"topic"`
	Params *UnsubscribeWalletSwapsParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeWalletSwaps) GetMethod() string {
	if u == nil {
		return ""
	}
	return u.Method
}

func (u *UnsubscribeWalletSwaps) GetTopic() string {
	if u == nil {
		return ""
	}
	return u.Topic
}

func (u *UnsubscribeWalletSwaps) GetParams() *UnsubscribeWalletSwapsParams {
	if u == nil {
		return nil
	}
	return u.Params
}

func (u *UnsubscribeWalletSwaps) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeWalletSwaps) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletSwaps) SetMethod(method string) {
	u.Method = method
	u.require(unsubscribeWalletSwapsFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletSwaps) SetTopic(topic string) {
	u.Topic = topic
	u.require(unsubscribeWalletSwapsFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletSwaps) SetParams(params *UnsubscribeWalletSwapsParams) {
	u.Params = params
	u.require(unsubscribeWalletSwapsFieldParams)
}

func (u *UnsubscribeWalletSwaps) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeWalletSwaps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeWalletSwaps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeWalletSwaps) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeWalletSwaps
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeWalletSwaps) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribeWalletSwapsParamsFieldWallets = big.NewInt(1 << 0)
)

type UnsubscribeWalletSwapsParams struct {
	Wallets []string `json:"wallets,omitempty" url:"wallets,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribeWalletSwapsParams) GetWallets() []string {
	if u == nil {
		return nil
	}
	return u.Wallets
}

func (u *UnsubscribeWalletSwapsParams) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribeWalletSwapsParams) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetWallets sets the Wallets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribeWalletSwapsParams) SetWallets(wallets []string) {
	u.Wallets = wallets
	u.require(unsubscribeWalletSwapsParamsFieldWallets)
}

func (u *UnsubscribeWalletSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribeWalletSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribeWalletSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribeWalletSwapsParams) MarshalJSON() ([]byte, error) {
	type embed UnsubscribeWalletSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribeWalletSwapsParams) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	walletSwapsSubscriptionMessageFieldTopic = big.NewInt(1 << 0)
	walletSwapsSubscriptionMessageFieldData  = big.NewInt(1 << 1)
)

type WalletSwapsSubscriptionMessage struct {
	Topic *string                             `json:"topic,omitempty" url:"topic,omitempty"`
	Data  *WalletSwapsSubscriptionMessageData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletSwapsSubscriptionMessage) GetTopic() *string {
	if w == nil {
		return nil
	}
	return w.Topic
}

func (w *WalletSwapsSubscriptionMessage) GetData() *WalletSwapsSubscriptionMessageData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WalletSwapsSubscriptionMessage) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletSwapsSubscriptionMessage) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessage) SetTopic(topic *string) {
	w.Topic = topic
	w.require(walletSwapsSubscriptionMessageFieldTopic)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessage) SetData(data *WalletSwapsSubscriptionMessageData) {
	w.Data = data
	w.require(walletSwapsSubscriptionMessageFieldData)
}

func (w *WalletSwapsSubscriptionMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler WalletSwapsSubscriptionMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WalletSwapsSubscriptionMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletSwapsSubscriptionMessage) MarshalJSON() ([]byte, error) {
	type embed WalletSwapsSubscriptionMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletSwapsSubscriptionMessage) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletSwapsSubscriptionMessageDataFieldID                  = big.NewInt(1 << 0)
	walletSwapsSubscriptionMessageDataFieldSwapType            = big.NewInt(1 << 1)
	walletSwapsSubscriptionMessageDataFieldProtocol            = big.NewInt(1 << 2)
	walletSwapsSubscriptionMessageDataFieldWalletAddress       = big.NewInt(1 << 3)
	walletSwapsSubscriptionMessageDataFieldTokenAddressIn      = big.NewInt(1 << 4)
	walletSwapsSubscriptionMessageDataFieldTokenAddressOut     = big.NewInt(1 << 5)
	walletSwapsSubscriptionMessageDataFieldTokenAmountIn       = big.NewInt(1 << 6)
	walletSwapsSubscriptionMessageDataFieldTokenAmountOut      = big.NewInt(1 << 7)
	walletSwapsSubscriptionMessageDataFieldTokenPriceIn        = big.NewInt(1 << 8)
	walletSwapsSubscriptionMessageDataFieldTokenPriceOut       = big.NewInt(1 << 9)
	walletSwapsSubscriptionMessageDataFieldPreTokenBalanceIn   = big.NewInt(1 << 10)
	walletSwapsSubscriptionMessageDataFieldPreTokenBalanceOut  = big.NewInt(1 << 11)
	walletSwapsSubscriptionMessageDataFieldPostTokenBalanceIn  = big.NewInt(1 << 12)
	walletSwapsSubscriptionMessageDataFieldPostTokenBalanceOut = big.NewInt(1 << 13)
	walletSwapsSubscriptionMessageDataFieldUsdAmountIn         = big.NewInt(1 << 14)
	walletSwapsSubscriptionMessageDataFieldUsdAmountOut        = big.NewInt(1 << 15)
	walletSwapsSubscriptionMessageDataFieldBlockSlot           = big.NewInt(1 << 16)
	walletSwapsSubscriptionMessageDataFieldBlockTime           = big.NewInt(1 << 17)
	walletSwapsSubscriptionMessageDataFieldTxHash              = big.NewInt(1 << 18)
)

type WalletSwapsSubscriptionMessageData struct {
	ID       *int                                        `json:"id,omitempty" url:"id,omitempty"`
	SwapType *WalletSwapsSubscriptionMessageDataSwapType `json:"swap_type,omitempty" url:"swap_type,omitempty"`
	// Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols.
	Protocol            *string    `json:"protocol,omitempty" url:"protocol,omitempty"`
	WalletAddress       *string    `json:"wallet_address,omitempty" url:"wallet_address,omitempty"`
	TokenAddressIn      *string    `json:"token_address_in,omitempty" url:"token_address_in,omitempty"`
	TokenAddressOut     *string    `json:"token_address_out,omitempty" url:"token_address_out,omitempty"`
	TokenAmountIn       *float64   `json:"token_amount_in,omitempty" url:"token_amount_in,omitempty"`
	TokenAmountOut      *float64   `json:"token_amount_out,omitempty" url:"token_amount_out,omitempty"`
	TokenPriceIn        *float64   `json:"token_price_in,omitempty" url:"token_price_in,omitempty"`
	TokenPriceOut       *float64   `json:"token_price_out,omitempty" url:"token_price_out,omitempty"`
	PreTokenBalanceIn   *float64   `json:"pre_token_balance_in,omitempty" url:"pre_token_balance_in,omitempty"`
	PreTokenBalanceOut  *float64   `json:"pre_token_balance_out,omitempty" url:"pre_token_balance_out,omitempty"`
	PostTokenBalanceIn  *float64   `json:"post_token_balance_in,omitempty" url:"post_token_balance_in,omitempty"`
	PostTokenBalanceOut *float64   `json:"post_token_balance_out,omitempty" url:"post_token_balance_out,omitempty"`
	UsdAmountIn         *float64   `json:"usd_amount_in,omitempty" url:"usd_amount_in,omitempty"`
	UsdAmountOut        *float64   `json:"usd_amount_out,omitempty" url:"usd_amount_out,omitempty"`
	BlockSlot           *int       `json:"block_slot,omitempty" url:"block_slot,omitempty"`
	BlockTime           *time.Time `json:"block_time,omitempty" url:"block_time,omitempty"`
	TxHash              *string    `json:"tx_hash,omitempty" url:"tx_hash,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletSwapsSubscriptionMessageData) GetID() *int {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WalletSwapsSubscriptionMessageData) GetSwapType() *WalletSwapsSubscriptionMessageDataSwapType {
	if w == nil {
		return nil
	}
	return w.SwapType
}

func (w *WalletSwapsSubscriptionMessageData) GetProtocol() *string {
	if w == nil {
		return nil
	}
	return w.Protocol
}

func (w *WalletSwapsSubscriptionMessageData) GetWalletAddress() *string {
	if w == nil {
		return nil
	}
	return w.WalletAddress
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenAddressIn() *string {
	if w == nil {
		return nil
	}
	return w.TokenAddressIn
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenAddressOut() *string {
	if w == nil {
		return nil
	}
	return w.TokenAddressOut
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenAmountIn() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenAmountIn
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenAmountOut() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenAmountOut
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenPriceIn() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenPriceIn
}

func (w *WalletSwapsSubscriptionMessageData) GetTokenPriceOut() *float64 {
	if w == nil {
		return nil
	}
	return w.TokenPriceOut
}

func (w *WalletSwapsSubscriptionMessageData) GetPreTokenBalanceIn() *float64 {
	if w == nil {
		return nil
	}
	return w.PreTokenBalanceIn
}

func (w *WalletSwapsSubscriptionMessageData) GetPreTokenBalanceOut() *float64 {
	if w == nil {
		return nil
	}
	return w.PreTokenBalanceOut
}

func (w *WalletSwapsSubscriptionMessageData) GetPostTokenBalanceIn() *float64 {
	if w == nil {
		return nil
	}
	return w.PostTokenBalanceIn
}

func (w *WalletSwapsSubscriptionMessageData) GetPostTokenBalanceOut() *float64 {
	if w == nil {
		return nil
	}
	return w.PostTokenBalanceOut
}

func (w *WalletSwapsSubscriptionMessageData) GetUsdAmountIn() *float64 {
	if w == nil {
		return nil
	}
	return w.UsdAmountIn
}

func (w *WalletSwapsSubscriptionMessageData) GetUsdAmountOut() *float64 {
	if w == nil {
		return nil
	}
	return w.UsdAmountOut
}

func (w *WalletSwapsSubscriptionMessageData) GetBlockSlot() *int {
	if w == nil {
		return nil
	}
	return w.BlockSlot
}

func (w *WalletSwapsSubscriptionMessageData) GetBlockTime() *time.Time {
	if w == nil {
		return nil
	}
	return w.BlockTime
}

func (w *WalletSwapsSubscriptionMessageData) GetTxHash() *string {
	if w == nil {
		return nil
	}
	return w.TxHash
}

func (w *WalletSwapsSubscriptionMessageData) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletSwapsSubscriptionMessageData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetID(id *int) {
	w.ID = id
	w.require(walletSwapsSubscriptionMessageDataFieldID)
}

// SetSwapType sets the SwapType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetSwapType(swapType *WalletSwapsSubscriptionMessageDataSwapType) {
	w.SwapType = swapType
	w.require(walletSwapsSubscriptionMessageDataFieldSwapType)
}

// SetProtocol sets the Protocol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetProtocol(protocol *string) {
	w.Protocol = protocol
	w.require(walletSwapsSubscriptionMessageDataFieldProtocol)
}

// SetWalletAddress sets the WalletAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetWalletAddress(walletAddress *string) {
	w.WalletAddress = walletAddress
	w.require(walletSwapsSubscriptionMessageDataFieldWalletAddress)
}

// SetTokenAddressIn sets the TokenAddressIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenAddressIn(tokenAddressIn *string) {
	w.TokenAddressIn = tokenAddressIn
	w.require(walletSwapsSubscriptionMessageDataFieldTokenAddressIn)
}

// SetTokenAddressOut sets the TokenAddressOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenAddressOut(tokenAddressOut *string) {
	w.TokenAddressOut = tokenAddressOut
	w.require(walletSwapsSubscriptionMessageDataFieldTokenAddressOut)
}

// SetTokenAmountIn sets the TokenAmountIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenAmountIn(tokenAmountIn *float64) {
	w.TokenAmountIn = tokenAmountIn
	w.require(walletSwapsSubscriptionMessageDataFieldTokenAmountIn)
}

// SetTokenAmountOut sets the TokenAmountOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenAmountOut(tokenAmountOut *float64) {
	w.TokenAmountOut = tokenAmountOut
	w.require(walletSwapsSubscriptionMessageDataFieldTokenAmountOut)
}

// SetTokenPriceIn sets the TokenPriceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenPriceIn(tokenPriceIn *float64) {
	w.TokenPriceIn = tokenPriceIn
	w.require(walletSwapsSubscriptionMessageDataFieldTokenPriceIn)
}

// SetTokenPriceOut sets the TokenPriceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTokenPriceOut(tokenPriceOut *float64) {
	w.TokenPriceOut = tokenPriceOut
	w.require(walletSwapsSubscriptionMessageDataFieldTokenPriceOut)
}

// SetPreTokenBalanceIn sets the PreTokenBalanceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetPreTokenBalanceIn(preTokenBalanceIn *float64) {
	w.PreTokenBalanceIn = preTokenBalanceIn
	w.require(walletSwapsSubscriptionMessageDataFieldPreTokenBalanceIn)
}

// SetPreTokenBalanceOut sets the PreTokenBalanceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetPreTokenBalanceOut(preTokenBalanceOut *float64) {
	w.PreTokenBalanceOut = preTokenBalanceOut
	w.require(walletSwapsSubscriptionMessageDataFieldPreTokenBalanceOut)
}

// SetPostTokenBalanceIn sets the PostTokenBalanceIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetPostTokenBalanceIn(postTokenBalanceIn *float64) {
	w.PostTokenBalanceIn = postTokenBalanceIn
	w.require(walletSwapsSubscriptionMessageDataFieldPostTokenBalanceIn)
}

// SetPostTokenBalanceOut sets the PostTokenBalanceOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetPostTokenBalanceOut(postTokenBalanceOut *float64) {
	w.PostTokenBalanceOut = postTokenBalanceOut
	w.require(walletSwapsSubscriptionMessageDataFieldPostTokenBalanceOut)
}

// SetUsdAmountIn sets the UsdAmountIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetUsdAmountIn(usdAmountIn *float64) {
	w.UsdAmountIn = usdAmountIn
	w.require(walletSwapsSubscriptionMessageDataFieldUsdAmountIn)
}

// SetUsdAmountOut sets the UsdAmountOut field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetUsdAmountOut(usdAmountOut *float64) {
	w.UsdAmountOut = usdAmountOut
	w.require(walletSwapsSubscriptionMessageDataFieldUsdAmountOut)
}

// SetBlockSlot sets the BlockSlot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetBlockSlot(blockSlot *int) {
	w.BlockSlot = blockSlot
	w.require(walletSwapsSubscriptionMessageDataFieldBlockSlot)
}

// SetBlockTime sets the BlockTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetBlockTime(blockTime *time.Time) {
	w.BlockTime = blockTime
	w.require(walletSwapsSubscriptionMessageDataFieldBlockTime)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletSwapsSubscriptionMessageData) SetTxHash(txHash *string) {
	w.TxHash = txHash
	w.require(walletSwapsSubscriptionMessageDataFieldTxHash)
}

func (w *WalletSwapsSubscriptionMessageData) UnmarshalJSON(data []byte) error {
	type embed WalletSwapsSubscriptionMessageData
	var unmarshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletSwapsSubscriptionMessageData(unmarshaler.embed)
	w.BlockTime = unmarshaler.BlockTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletSwapsSubscriptionMessageData) MarshalJSON() ([]byte, error) {
	type embed WalletSwapsSubscriptionMessageData
	var marshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed:     embed(*w),
		BlockTime: internal.NewOptionalDateTime(w.BlockTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletSwapsSubscriptionMessageData) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WalletSwapsSubscriptionMessageDataSwapType string

const (
	WalletSwapsSubscriptionMessageDataSwapTypeQuoteToken WalletSwapsSubscriptionMessageDataSwapType = "quote_token"
	WalletSwapsSubscriptionMessageDataSwapTypeTokenQuote WalletSwapsSubscriptionMessageDataSwapType = "token_quote"
	WalletSwapsSubscriptionMessageDataSwapTypeTokenToken WalletSwapsSubscriptionMessageDataSwapType = "token_token"
	WalletSwapsSubscriptionMessageDataSwapTypeQuoteQuote WalletSwapsSubscriptionMessageDataSwapType = "quote_quote"
)

func NewWalletSwapsSubscriptionMessageDataSwapTypeFromString(s string) (WalletSwapsSubscriptionMessageDataSwapType, error) {
	switch s {
	case "quote_token":
		return WalletSwapsSubscriptionMessageDataSwapTypeQuoteToken, nil
	case "token_quote":
		return WalletSwapsSubscriptionMessageDataSwapTypeTokenQuote, nil
	case "token_token":
		return WalletSwapsSubscriptionMessageDataSwapTypeTokenToken, nil
	case "quote_quote":
		return WalletSwapsSubscriptionMessageDataSwapTypeQuoteQuote, nil
	}
	var t WalletSwapsSubscriptionMessageDataSwapType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WalletSwapsSubscriptionMessageDataSwapType) Ptr() *WalletSwapsSubscriptionMessageDataSwapType {
	return &w
}
