// Code generated by Fern. DO NOT EDIT.

package prism

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	pricesSubscriptionMessageFieldTopic = big.NewInt(1 << 0)
	pricesSubscriptionMessageFieldData  = big.NewInt(1 << 1)
)

type PricesSubscriptionMessage struct {
	Topic *string                        `json:"topic,omitempty" url:"topic,omitempty"`
	Data  *PricesSubscriptionMessageData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PricesSubscriptionMessage) GetTopic() *string {
	if p == nil {
		return nil
	}
	return p.Topic
}

func (p *PricesSubscriptionMessage) GetData() *PricesSubscriptionMessageData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PricesSubscriptionMessage) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PricesSubscriptionMessage) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessage) SetTopic(topic *string) {
	p.Topic = topic
	p.require(pricesSubscriptionMessageFieldTopic)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessage) SetData(data *PricesSubscriptionMessageData) {
	p.Data = data
	p.require(pricesSubscriptionMessageFieldData)
}

func (p *PricesSubscriptionMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler PricesSubscriptionMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PricesSubscriptionMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PricesSubscriptionMessage) MarshalJSON() ([]byte, error) {
	type embed PricesSubscriptionMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PricesSubscriptionMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	pricesSubscriptionMessageDataFieldTokenAddress = big.NewInt(1 << 0)
	pricesSubscriptionMessageDataFieldUsdPrice     = big.NewInt(1 << 1)
	pricesSubscriptionMessageDataFieldBlockSlot    = big.NewInt(1 << 2)
	pricesSubscriptionMessageDataFieldBlockTime    = big.NewInt(1 << 3)
)

type PricesSubscriptionMessageData struct {
	TokenAddress *string    `json:"token_address,omitempty" url:"token_address,omitempty"`
	UsdPrice     *float64   `json:"usd_price,omitempty" url:"usd_price,omitempty"`
	BlockSlot    *int       `json:"block_slot,omitempty" url:"block_slot,omitempty"`
	BlockTime    *time.Time `json:"block_time,omitempty" url:"block_time,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PricesSubscriptionMessageData) GetTokenAddress() *string {
	if p == nil {
		return nil
	}
	return p.TokenAddress
}

func (p *PricesSubscriptionMessageData) GetUsdPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.UsdPrice
}

func (p *PricesSubscriptionMessageData) GetBlockSlot() *int {
	if p == nil {
		return nil
	}
	return p.BlockSlot
}

func (p *PricesSubscriptionMessageData) GetBlockTime() *time.Time {
	if p == nil {
		return nil
	}
	return p.BlockTime
}

func (p *PricesSubscriptionMessageData) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PricesSubscriptionMessageData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetTokenAddress sets the TokenAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessageData) SetTokenAddress(tokenAddress *string) {
	p.TokenAddress = tokenAddress
	p.require(pricesSubscriptionMessageDataFieldTokenAddress)
}

// SetUsdPrice sets the UsdPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessageData) SetUsdPrice(usdPrice *float64) {
	p.UsdPrice = usdPrice
	p.require(pricesSubscriptionMessageDataFieldUsdPrice)
}

// SetBlockSlot sets the BlockSlot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessageData) SetBlockSlot(blockSlot *int) {
	p.BlockSlot = blockSlot
	p.require(pricesSubscriptionMessageDataFieldBlockSlot)
}

// SetBlockTime sets the BlockTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PricesSubscriptionMessageData) SetBlockTime(blockTime *time.Time) {
	p.BlockTime = blockTime
	p.require(pricesSubscriptionMessageDataFieldBlockTime)
}

func (p *PricesSubscriptionMessageData) UnmarshalJSON(data []byte) error {
	type embed PricesSubscriptionMessageData
	var unmarshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PricesSubscriptionMessageData(unmarshaler.embed)
	p.BlockTime = unmarshaler.BlockTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PricesSubscriptionMessageData) MarshalJSON() ([]byte, error) {
	type embed PricesSubscriptionMessageData
	var marshaler = struct {
		embed
		BlockTime *internal.DateTime `json:"block_time,omitempty"`
	}{
		embed:     embed(*p),
		BlockTime: internal.NewOptionalDateTime(p.BlockTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PricesSubscriptionMessageData) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	subscribePricesFieldMethod = big.NewInt(1 << 0)
	subscribePricesFieldTopic  = big.NewInt(1 << 1)
	subscribePricesFieldParams = big.NewInt(1 << 2)
)

type SubscribePrices struct {
	Method string                 `json:"method" url:"method"`
	Topic  string                 `json:"topic" url:"topic"`
	Params *SubscribePricesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribePrices) GetMethod() string {
	if s == nil {
		return ""
	}
	return s.Method
}

func (s *SubscribePrices) GetTopic() string {
	if s == nil {
		return ""
	}
	return s.Topic
}

func (s *SubscribePrices) GetParams() *SubscribePricesParams {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SubscribePrices) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribePrices) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribePrices) SetMethod(method string) {
	s.Method = method
	s.require(subscribePricesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribePrices) SetTopic(topic string) {
	s.Topic = topic
	s.require(subscribePricesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribePrices) SetParams(params *SubscribePricesParams) {
	s.Params = params
	s.require(subscribePricesFieldParams)
}

func (s *SubscribePrices) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribePrices
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribePrices(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribePrices) MarshalJSON() ([]byte, error) {
	type embed SubscribePrices
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribePrices) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribePricesParamsFieldTokens = big.NewInt(1 << 0)
)

type SubscribePricesParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribePricesParams) GetTokens() []string {
	if s == nil {
		return nil
	}
	return s.Tokens
}

func (s *SubscribePricesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribePricesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribePricesParams) SetTokens(tokens []string) {
	s.Tokens = tokens
	s.require(subscribePricesParamsFieldTokens)
}

func (s *SubscribePricesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribePricesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribePricesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribePricesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribePricesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribePricesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	unsubscribePricesFieldMethod = big.NewInt(1 << 0)
	unsubscribePricesFieldTopic  = big.NewInt(1 << 1)
	unsubscribePricesFieldParams = big.NewInt(1 << 2)
)

type UnsubscribePrices struct {
	Method string                   `json:"method" url:"method"`
	Topic  string                   `json:"topic" url:"topic"`
	Params *UnsubscribePricesParams `json:"params" url:"params"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribePrices) GetMethod() string {
	if u == nil {
		return ""
	}
	return u.Method
}

func (u *UnsubscribePrices) GetTopic() string {
	if u == nil {
		return ""
	}
	return u.Topic
}

func (u *UnsubscribePrices) GetParams() *UnsubscribePricesParams {
	if u == nil {
		return nil
	}
	return u.Params
}

func (u *UnsubscribePrices) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribePrices) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribePrices) SetMethod(method string) {
	u.Method = method
	u.require(unsubscribePricesFieldMethod)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribePrices) SetTopic(topic string) {
	u.Topic = topic
	u.require(unsubscribePricesFieldTopic)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribePrices) SetParams(params *UnsubscribePricesParams) {
	u.Params = params
	u.require(unsubscribePricesFieldParams)
}

func (u *UnsubscribePrices) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribePrices
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribePrices(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribePrices) MarshalJSON() ([]byte, error) {
	type embed UnsubscribePrices
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribePrices) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unsubscribePricesParamsFieldTokens = big.NewInt(1 << 0)
)

type UnsubscribePricesParams struct {
	Tokens []string `json:"tokens,omitempty" url:"tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnsubscribePricesParams) GetTokens() []string {
	if u == nil {
		return nil
	}
	return u.Tokens
}

func (u *UnsubscribePricesParams) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnsubscribePricesParams) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnsubscribePricesParams) SetTokens(tokens []string) {
	u.Tokens = tokens
	u.require(unsubscribePricesParamsFieldTokens)
}

func (u *UnsubscribePricesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler UnsubscribePricesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnsubscribePricesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnsubscribePricesParams) MarshalJSON() ([]byte, error) {
	type embed UnsubscribePricesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnsubscribePricesParams) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
