// Code generated by Fern. DO NOT EDIT.

package client

import (
	client "github.com/prism-api/sdk-go/api/solana/client"
	core "github.com/prism-api/sdk-go/core"
	internal "github.com/prism-api/sdk-go/internal"
)

type Client struct {
	Solana *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Solana:  client.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
