// Code generated by Fern. DO NOT EDIT.

package solana_dex_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	prism "github.com/prism-api/sdk-go"
	client "github.com/prism-api/sdk-go/client"
	option "github.com/prism-api/sdk-go/option"
	solana "github.com/prism-api/sdk-go/solana"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSolanaDexGetWalletProfileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetWalletProfileDexRequest{
		Wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		Options: &prism.SolanaDexWalletProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []prism.SolanaDexWalletProfileTimeWindowEnum{
				prism.SolanaDexWalletProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.Solana.Dex.GetWalletProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetWalletProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetWalletProfileWithWireMock", "POST", "/v1/solana/dex/profiles/wallets/get-profile", nil, 1)
}

func TestSolanaDexSearchWalletProfilesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.SearchWalletProfilesDexRequest{
		Limit: prism.Int(
			10,
		),
		Query: &prism.SolanaDexWalletProfileSearchPayloadQuery{
			Text: "cupsey",
			Fields: []prism.SolanaDexWalletProfileSearchPayloadQueryTargetsEnum{
				prism.SolanaDexWalletProfileSearchPayloadQueryTargetsEnumWalletAddress,
			},
		},
		Sort: &prism.SolanaDexProfileSearchPayloadSort{
			Field:     "metrics.7d.cumulative_pnl",
			Direction: prism.SolanaDexProfileSearchPayloadSortDirectionEnumDesc,
		},
		DynamicLabels: &prism.SolanaDexProfileSearchPayloadDynamicLabels{
			"smart": &prism.SolanaDexProfileSearchPayloadFilter{},
		},
		Options: &prism.SolanaDexWalletProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []prism.SolanaDexWalletProfileTimeWindowEnum{
				prism.SolanaDexWalletProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.Solana.Dex.SearchWalletProfiles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexSearchWalletProfilesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexSearchWalletProfilesWithWireMock", "POST", "/v1/solana/dex/profiles/wallets/search-profiles", nil, 1)
}

func TestSolanaDexGetTokenProfileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetTokenProfileDexRequest{
		Token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		Options: &prism.SolanaDexTokenProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeMarket: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []prism.SolanaDexTokenProfileTimeWindowEnum{
				prism.SolanaDexTokenProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.Solana.Dex.GetTokenProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetTokenProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetTokenProfileWithWireMock", "POST", "/v1/solana/dex/profiles/tokens/get-profile", nil, 1)
}

func TestSolanaDexSearchTokenProfilesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.SearchTokenProfilesDexRequest{
		Limit: prism.Int(
			10,
		),
		Query: &prism.SolanaDexTokenProfileSearchPayloadQueryField{
			Text: "bonk",
			Fields: []prism.SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum{
				prism.SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnumMetadataName,
			},
		},
		Sort: &prism.SolanaDexProfileSearchPayloadSort{
			Field:     "market.liquidity",
			Direction: prism.SolanaDexProfileSearchPayloadSortDirectionEnumDesc,
		},
		DynamicLabels: &prism.SolanaDexProfileSearchPayloadDynamicLabels{
			"trending": &prism.SolanaDexProfileSearchPayloadFilter{},
		},
		Options: &prism.SolanaDexTokenProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeMarket: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []prism.SolanaDexTokenProfileTimeWindowEnum{
				prism.SolanaDexTokenProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.Solana.Dex.SearchTokenProfiles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexSearchTokenProfilesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexSearchTokenProfilesWithWireMock", "POST", "/v1/solana/dex/profiles/tokens/search-profiles", nil, 1)
}

func TestSolanaDexGetTradesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetTradesDexRequest{
		Limit: prism.Int(
			20,
		),
		Wallet: prism.String(
			"suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		),
	}
	_, invocationErr := client.Solana.Dex.GetTrades(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetTradesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetTradesWithWireMock", "POST", "/v1/solana/dex/trades/get-trades", nil, 1)
}

func TestSolanaDexGetSwapsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetSwapsDexRequest{
		Limit: prism.Int(
			20,
		),
		Wallet: prism.String(
			"suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		),
	}
	_, invocationErr := client.Solana.Dex.GetSwaps(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetSwapsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetSwapsWithWireMock", "POST", "/v1/solana/dex/swaps/get-swaps", nil, 1)
}

func TestSolanaDexGetPriceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
	}
	_, invocationErr := client.Solana.Dex.GetPrice(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetPriceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetPriceWithWireMock", "POST", "/v1/solana/dex/prices/get-price", nil, 1)
}

func TestSolanaDexGetPriceStatsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceStatsDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
	}
	_, invocationErr := client.Solana.Dex.GetPriceStats(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetPriceStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetPriceStatsWithWireMock", "POST", "/v1/solana/dex/prices/get-price-stats", nil, 1)
}

func TestSolanaDexGetPriceCandlesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceCandlesDexRequest{
		Token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		From: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T00:00:00Z",
			),
		),
		To: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T01:00:00Z",
			),
		),
		Interval: 60,
	}
	_, invocationErr := client.Solana.Dex.GetPriceCandles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetPriceCandlesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetPriceCandlesWithWireMock", "POST", "/v1/solana/dex/prices/get-price-candles", nil, 1)
}

func TestSolanaDexGetPriceHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceHistoryDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
		From: prism.MustParseDateTime(
			"2026-04-27T00:00:00Z",
		),
		To: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T01:00:00Z",
			),
		),
		Interval: 3600,
	}
	_, invocationErr := client.Solana.Dex.GetPriceHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSolanaDexGetPriceHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSolanaDexGetPriceHistoryWithWireMock", "POST", "/v1/solana/dex/prices/get-price-history", nil, 1)
}
