// Code generated by Fern. DO NOT EDIT.

package api_solana_dex_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	prism "github.com/prism-api/sdk-go"
	api "github.com/prism-api/sdk-go/api"
	solana "github.com/prism-api/sdk-go/api/solana"
	client "github.com/prism-api/sdk-go/client"
	option "github.com/prism-api/sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAPISolanaDexGetWalletProfileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetWalletProfileDexRequest{
		Wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		Options: &api.SolanaDexWalletProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []api.SolanaDexWalletProfileTimeWindowEnum{
				api.SolanaDexWalletProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.API.Solana.Dex.GetWalletProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetWalletProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetWalletProfileWithWireMock", "POST", "/v1/solana/dex/profiles/wallets/get-profile", nil, 1)
}

func TestAPISolanaDexSearchWalletProfilesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.SearchWalletProfilesDexRequest{
		Limit: prism.Int(
			10,
		),
		Query: &api.SolanaDexWalletProfileSearchPayloadQuery{
			Text: "cupsey",
			Fields: []api.SolanaDexWalletProfileSearchPayloadQueryTargetsEnum{
				api.SolanaDexWalletProfileSearchPayloadQueryTargetsEnumIdentityName,
			},
		},
		Sort: &api.SolanaDexProfileSearchPayloadSort{
			Field:     "metrics.7d.cumulative_pnl",
			Direction: api.SolanaDexProfileSearchPayloadSortDirectionEnumDesc,
		},
		DynamicLabels: &api.SolanaDexProfileSearchPayloadDynamicLabels{
			"smart": &api.SolanaDexProfileSearchPayloadFilter{},
		},
		Options: &api.SolanaDexWalletProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []api.SolanaDexWalletProfileTimeWindowEnum{
				api.SolanaDexWalletProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.API.Solana.Dex.SearchWalletProfiles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexSearchWalletProfilesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexSearchWalletProfilesWithWireMock", "POST", "/v1/solana/dex/profiles/wallets/search-profiles", nil, 1)
}

func TestAPISolanaDexGetTokenProfileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetTokenProfileDexRequest{
		Token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		Options: &api.SolanaDexTokenProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeMarket: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []api.SolanaDexTokenProfileTimeWindowEnum{
				api.SolanaDexTokenProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.API.Solana.Dex.GetTokenProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetTokenProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetTokenProfileWithWireMock", "POST", "/v1/solana/dex/profiles/tokens/get-profile", nil, 1)
}

func TestAPISolanaDexSearchTokenProfilesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.SearchTokenProfilesDexRequest{
		Limit: prism.Int(
			10,
		),
		Query: &api.SolanaDexTokenProfileSearchPayloadQueryField{
			Text: "bonk",
			Fields: []api.SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnum{
				api.SolanaDexTokenProfileSearchPayloadQueryFieldTargetsEnumMetadataName,
			},
		},
		Sort: &api.SolanaDexProfileSearchPayloadSort{
			Field:     "market.liquidity",
			Direction: api.SolanaDexProfileSearchPayloadSortDirectionEnumDesc,
		},
		DynamicLabels: &api.SolanaDexProfileSearchPayloadDynamicLabels{
			"trending": &api.SolanaDexProfileSearchPayloadFilter{},
		},
		Options: &api.SolanaDexTokenProfilePayloadOptions{
			IncludeMetadata: prism.Bool(
				true,
			),
			IncludeMarket: prism.Bool(
				true,
			),
			IncludeLabels: prism.Bool(
				true,
			),
			IncludeMetrics: []api.SolanaDexTokenProfileTimeWindowEnum{
				api.SolanaDexTokenProfileTimeWindowEnumWindow7D,
			},
		},
	}
	_, invocationErr := client.API.Solana.Dex.SearchTokenProfiles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexSearchTokenProfilesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexSearchTokenProfilesWithWireMock", "POST", "/v1/solana/dex/profiles/tokens/search-profiles", nil, 1)
}

func TestAPISolanaDexGetTradesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetTradesDexRequest{
		Limit: prism.Int(
			20,
		),
		Wallet: prism.String(
			"suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		),
	}
	_, invocationErr := client.API.Solana.Dex.GetTrades(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetTradesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetTradesWithWireMock", "POST", "/v1/solana/dex/trades/get-trades", nil, 1)
}

func TestAPISolanaDexGetSwapsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetSwapsDexRequest{
		Limit: prism.Int(
			20,
		),
		Wallet: prism.String(
			"suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
		),
	}
	_, invocationErr := client.API.Solana.Dex.GetSwaps(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetSwapsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetSwapsWithWireMock", "POST", "/v1/solana/dex/swaps/get-swaps", nil, 1)
}

func TestAPISolanaDexGetPriceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
	}
	_, invocationErr := client.API.Solana.Dex.GetPrice(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetPriceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetPriceWithWireMock", "POST", "/v1/solana/dex/prices/get-price", nil, 1)
}

func TestAPISolanaDexGetPriceStatsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceStatsDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
	}
	_, invocationErr := client.API.Solana.Dex.GetPriceStats(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetPriceStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetPriceStatsWithWireMock", "POST", "/v1/solana/dex/prices/get-price-stats", nil, 1)
}

func TestAPISolanaDexGetPriceCandlesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceCandlesDexRequest{
		Token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		From: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T00:00:00Z",
			),
		),
		To: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T01:00:00Z",
			),
		),
		Interval: 60,
	}
	_, invocationErr := client.API.Solana.Dex.GetPriceCandles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetPriceCandlesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetPriceCandlesWithWireMock", "POST", "/v1/solana/dex/prices/get-price-candles", nil, 1)
}

func TestAPISolanaDexGetPriceHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &solana.GetPriceHistoryDexRequest{
		Tokens: []string{
			"Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
		},
		From: prism.MustParseDateTime(
			"2026-04-27T00:00:00Z",
		),
		To: prism.Time(
			prism.MustParseDateTime(
				"2026-04-27T01:00:00Z",
			),
		),
		Interval: 3600,
	}
	_, invocationErr := client.API.Solana.Dex.GetPriceHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAPISolanaDexGetPriceHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAPISolanaDexGetPriceHistoryWithWireMock", "POST", "/v1/solana/dex/prices/get-price-history", nil, 1)
}
