// Code generated by Fern. DO NOT EDIT.

package evm

import (
	json "encoding/json"
	fmt "fmt"
	api "github.com/prism-api/sdk-go/api"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	getPositionProfileDexRequestFieldChainID = big.NewInt(1 << 0)
	getPositionProfileDexRequestFieldWallet  = big.NewInt(1 << 1)
	getPositionProfileDexRequestFieldToken   = big.NewInt(1 << 2)
	getPositionProfileDexRequestFieldOptions = big.NewInt(1 << 3)
)

type GetPositionProfileDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Wallet address of the position to retrieve.
	Wallet string `json:"wallet" url:"-"`
	// Token address of the position to retrieve.
	Token   string                                   `json:"token" url:"-"`
	Options *api.EvmDexPositionProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPositionProfileDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPositionProfileDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getPositionProfileDexRequestFieldChainID)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPositionProfileDexRequest) SetWallet(wallet string) {
	g.Wallet = wallet
	g.require(getPositionProfileDexRequestFieldWallet)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPositionProfileDexRequest) SetToken(token string) {
	g.Token = token
	g.require(getPositionProfileDexRequestFieldToken)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPositionProfileDexRequest) SetOptions(options *api.EvmDexPositionProfilePayloadOptions) {
	g.Options = options
	g.require(getPositionProfileDexRequestFieldOptions)
}

func (g *GetPositionProfileDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPositionProfileDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPositionProfileDexRequest(body)
	return nil
}

func (g *GetPositionProfileDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPositionProfileDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceDexRequestFieldChainID = big.NewInt(1 << 0)
	getPriceDexRequestFieldTokens  = big.NewInt(1 << 1)
	getPriceDexRequestFieldPools   = big.NewInt(1 << 2)
)

type GetPriceDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Token addresses to retrieve the latest prices for.
	Tokens []string `json:"tokens,omitempty" url:"-"`
	// Pool addresses to retrieve the latest prices for.
	Pools []string `json:"pools,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getPriceDexRequestFieldChainID)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceDexRequestFieldTokens)
}

// SetPools sets the Pools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceDexRequest) SetPools(pools []string) {
	g.Pools = pools
	g.require(getPriceDexRequestFieldPools)
}

func (g *GetPriceDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceDexRequest(body)
	return nil
}

func (g *GetPriceDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceCandlesDexRequestFieldChainID  = big.NewInt(1 << 0)
	getPriceCandlesDexRequestFieldToken    = big.NewInt(1 << 1)
	getPriceCandlesDexRequestFieldPool     = big.NewInt(1 << 2)
	getPriceCandlesDexRequestFieldFrom     = big.NewInt(1 << 3)
	getPriceCandlesDexRequestFieldTo       = big.NewInt(1 << 4)
	getPriceCandlesDexRequestFieldCount    = big.NewInt(1 << 5)
	getPriceCandlesDexRequestFieldInterval = big.NewInt(1 << 6)
)

type GetPriceCandlesDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Token address to filter by.
	Token *string `json:"token,omitempty" url:"-"`
	// Pool address to filter by.
	Pool *string `json:"pool,omitempty" url:"-"`
	// Start of the candle range, as a date-time RFC3339 string.
	// Can be combined with `to` to define a bounded range.
	From *time.Time `json:"from,omitempty" url:"-"`
	// End of the candle range, as a date-time RFC3339 string.
	// Defaults to the current time.
	To *time.Time `json:"to,omitempty" url:"-"`
	// Number of candles to return.
	// Must be combined with `from` or `to`.
	Count *int `json:"count,omitempty" url:"-"`
	// Sampling interval between data points, in seconds.
	Interval int `json:"interval" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceCandlesDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getPriceCandlesDexRequestFieldChainID)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetToken(token *string) {
	g.Token = token
	g.require(getPriceCandlesDexRequestFieldToken)
}

// SetPool sets the Pool field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetPool(pool *string) {
	g.Pool = pool
	g.require(getPriceCandlesDexRequestFieldPool)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetFrom(from *time.Time) {
	g.From = from
	g.require(getPriceCandlesDexRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetTo(to *time.Time) {
	g.To = to
	g.require(getPriceCandlesDexRequestFieldTo)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetCount(count *int) {
	g.Count = count
	g.require(getPriceCandlesDexRequestFieldCount)
}

// SetInterval sets the Interval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetInterval(interval int) {
	g.Interval = interval
	g.require(getPriceCandlesDexRequestFieldInterval)
}

func (g *GetPriceCandlesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceCandlesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceCandlesDexRequest(body)
	return nil
}

func (g *GetPriceCandlesDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceCandlesDexRequest
	var marshaler = struct {
		embed
		From *internal.DateTime `json:"from,omitempty"`
		To   *internal.DateTime `json:"to,omitempty"`
	}{
		embed: embed(*g),
		From:  internal.NewOptionalDateTime(g.From),
		To:    internal.NewOptionalDateTime(g.To),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceHistoryDexRequestFieldChainID  = big.NewInt(1 << 0)
	getPriceHistoryDexRequestFieldTokens   = big.NewInt(1 << 1)
	getPriceHistoryDexRequestFieldPools    = big.NewInt(1 << 2)
	getPriceHistoryDexRequestFieldFrom     = big.NewInt(1 << 3)
	getPriceHistoryDexRequestFieldTo       = big.NewInt(1 << 4)
	getPriceHistoryDexRequestFieldInterval = big.NewInt(1 << 5)
)

type GetPriceHistoryDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Token addresses to retrieve price history for.
	Tokens []string `json:"tokens,omitempty" url:"-"`
	// Pool addresses to retrieve price history for.
	Pools []string `json:"pools,omitempty" url:"-"`
	// Start of the history range, as a date-time RFC3339 string.
	From time.Time `json:"from" url:"-"`
	// End of the history range, as a date-time RFC3339 string.
	// Defaults to the current time.
	To *time.Time `json:"to,omitempty" url:"-"`
	// Sampling interval between data points, in seconds.
	Interval int `json:"interval" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceHistoryDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getPriceHistoryDexRequestFieldChainID)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceHistoryDexRequestFieldTokens)
}

// SetPools sets the Pools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetPools(pools []string) {
	g.Pools = pools
	g.require(getPriceHistoryDexRequestFieldPools)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetFrom(from time.Time) {
	g.From = from
	g.require(getPriceHistoryDexRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetTo(to *time.Time) {
	g.To = to
	g.require(getPriceHistoryDexRequestFieldTo)
}

// SetInterval sets the Interval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetInterval(interval int) {
	g.Interval = interval
	g.require(getPriceHistoryDexRequestFieldInterval)
}

func (g *GetPriceHistoryDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceHistoryDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceHistoryDexRequest(body)
	return nil
}

func (g *GetPriceHistoryDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceHistoryDexRequest
	var marshaler = struct {
		embed
		From *internal.DateTime `json:"from"`
		To   *internal.DateTime `json:"to,omitempty"`
	}{
		embed: embed(*g),
		From:  internal.NewDateTime(g.From),
		To:    internal.NewOptionalDateTime(g.To),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceStatsDexRequestFieldChainID = big.NewInt(1 << 0)
	getPriceStatsDexRequestFieldTokens  = big.NewInt(1 << 1)
	getPriceStatsDexRequestFieldPools   = big.NewInt(1 << 2)
)

type GetPriceStatsDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Token addresses to retrieve price statistics for.
	Tokens []string `json:"tokens,omitempty" url:"-"`
	// Pool addresses to retrieve price statistics for.
	Pools []string `json:"pools,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceStatsDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceStatsDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getPriceStatsDexRequestFieldChainID)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceStatsDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceStatsDexRequestFieldTokens)
}

// SetPools sets the Pools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceStatsDexRequest) SetPools(pools []string) {
	g.Pools = pools
	g.require(getPriceStatsDexRequestFieldPools)
}

func (g *GetPriceStatsDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceStatsDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceStatsDexRequest(body)
	return nil
}

func (g *GetPriceStatsDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceStatsDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSwapsDexRequestFieldChainID = big.NewInt(1 << 0)
	getSwapsDexRequestFieldWallet  = big.NewInt(1 << 1)
	getSwapsDexRequestFieldToken   = big.NewInt(1 << 2)
	getSwapsDexRequestFieldPool    = big.NewInt(1 << 3)
)

type GetSwapsDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Wallet address to filter swaps by.
	Wallet *string `json:"wallet,omitempty" url:"-"`
	// Token address to filter swaps by.
	Token *string `json:"token,omitempty" url:"-"`
	// Pool address to filter swaps by.
	Pool *string `json:"pool,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSwapsDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getSwapsDexRequestFieldChainID)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetWallet(wallet *string) {
	g.Wallet = wallet
	g.require(getSwapsDexRequestFieldWallet)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetToken(token *string) {
	g.Token = token
	g.require(getSwapsDexRequestFieldToken)
}

// SetPool sets the Pool field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetPool(pool *string) {
	g.Pool = pool
	g.require(getSwapsDexRequestFieldPool)
}

func (g *GetSwapsDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSwapsDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetSwapsDexRequest(body)
	return nil
}

func (g *GetSwapsDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetSwapsDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getTokenProfileDexRequestFieldChainID = big.NewInt(1 << 0)
	getTokenProfileDexRequestFieldToken   = big.NewInt(1 << 1)
	getTokenProfileDexRequestFieldOptions = big.NewInt(1 << 2)
)

type GetTokenProfileDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Token address to retrieve the profile for.
	Token   string                                `json:"token" url:"-"`
	Options *api.EvmDexTokenProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTokenProfileDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTokenProfileDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getTokenProfileDexRequestFieldChainID)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTokenProfileDexRequest) SetToken(token string) {
	g.Token = token
	g.require(getTokenProfileDexRequestFieldToken)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTokenProfileDexRequest) SetOptions(options *api.EvmDexTokenProfilePayloadOptions) {
	g.Options = options
	g.require(getTokenProfileDexRequestFieldOptions)
}

func (g *GetTokenProfileDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTokenProfileDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetTokenProfileDexRequest(body)
	return nil
}

func (g *GetTokenProfileDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetTokenProfileDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getTradesDexRequestFieldChainID = big.NewInt(1 << 0)
	getTradesDexRequestFieldWallet  = big.NewInt(1 << 1)
	getTradesDexRequestFieldToken   = big.NewInt(1 << 2)
)

type GetTradesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Wallet address to filter trades by.
	Wallet *string `json:"wallet,omitempty" url:"-"`
	// Token address to filter trades by.
	Token *string `json:"token,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTradesDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getTradesDexRequestFieldChainID)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexRequest) SetWallet(wallet *string) {
	g.Wallet = wallet
	g.require(getTradesDexRequestFieldWallet)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexRequest) SetToken(token *string) {
	g.Token = token
	g.require(getTradesDexRequestFieldToken)
}

func (g *GetTradesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTradesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetTradesDexRequest(body)
	return nil
}

func (g *GetTradesDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetTradesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getWalletProfileDexRequestFieldChainID = big.NewInt(1 << 0)
	getWalletProfileDexRequestFieldWallet  = big.NewInt(1 << 1)
	getWalletProfileDexRequestFieldOptions = big.NewInt(1 << 2)
)

type GetWalletProfileDexRequest struct {
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"-"`
	// Wallet address to retrieve the profile for.
	Wallet  string                                 `json:"wallet" url:"-"`
	Options *api.EvmDexWalletProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWalletProfileDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletProfileDexRequest) SetChainID(chainID int) {
	g.ChainID = chainID
	g.require(getWalletProfileDexRequestFieldChainID)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletProfileDexRequest) SetWallet(wallet string) {
	g.Wallet = wallet
	g.require(getWalletProfileDexRequestFieldWallet)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletProfileDexRequest) SetOptions(options *api.EvmDexWalletProfilePayloadOptions) {
	g.Options = options
	g.require(getWalletProfileDexRequestFieldOptions)
}

func (g *GetWalletProfileDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetWalletProfileDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetWalletProfileDexRequest(body)
	return nil
}

func (g *GetWalletProfileDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetWalletProfileDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchPositionProfilesDexRequestFieldChainID = big.NewInt(1 << 0)
	searchPositionProfilesDexRequestFieldFilter  = big.NewInt(1 << 1)
	searchPositionProfilesDexRequestFieldSort    = big.NewInt(1 << 2)
	searchPositionProfilesDexRequestFieldOptions = big.NewInt(1 << 3)
)

type SearchPositionProfilesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int                                      `json:"chain_id" url:"-"`
	Filter  *api.EvmDexProfileSearchPayloadFilter    `json:"filter,omitempty" url:"-"`
	Sort    *api.EvmDexProfileSearchPayloadSort      `json:"sort,omitempty" url:"-"`
	Options *api.EvmDexPositionProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchPositionProfilesDexRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexRequest) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(searchPositionProfilesDexRequestFieldChainID)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexRequest) SetFilter(filter *api.EvmDexProfileSearchPayloadFilter) {
	s.Filter = filter
	s.require(searchPositionProfilesDexRequestFieldFilter)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexRequest) SetSort(sort *api.EvmDexProfileSearchPayloadSort) {
	s.Sort = sort
	s.require(searchPositionProfilesDexRequestFieldSort)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexRequest) SetOptions(options *api.EvmDexPositionProfilePayloadOptions) {
	s.Options = options
	s.require(searchPositionProfilesDexRequestFieldOptions)
}

func (s *SearchPositionProfilesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchPositionProfilesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchPositionProfilesDexRequest(body)
	return nil
}

func (s *SearchPositionProfilesDexRequest) MarshalJSON() ([]byte, error) {
	type embed SearchPositionProfilesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchTokenProfilesDexRequestFieldChainID = big.NewInt(1 << 0)
	searchTokenProfilesDexRequestFieldQuery   = big.NewInt(1 << 1)
	searchTokenProfilesDexRequestFieldFilter  = big.NewInt(1 << 2)
	searchTokenProfilesDexRequestFieldSort    = big.NewInt(1 << 3)
	searchTokenProfilesDexRequestFieldOptions = big.NewInt(1 << 4)
)

type SearchTokenProfilesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int                                            `json:"chain_id" url:"-"`
	Query   *api.EvmDexTokenProfileSearchPayloadQueryField `json:"query,omitempty" url:"-"`
	Filter  *api.EvmDexProfileSearchPayloadFilter          `json:"filter,omitempty" url:"-"`
	Sort    *api.EvmDexProfileSearchPayloadSort            `json:"sort,omitempty" url:"-"`
	Options *api.EvmDexTokenProfilePayloadOptions          `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchTokenProfilesDexRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(searchTokenProfilesDexRequestFieldChainID)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetQuery(query *api.EvmDexTokenProfileSearchPayloadQueryField) {
	s.Query = query
	s.require(searchTokenProfilesDexRequestFieldQuery)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetFilter(filter *api.EvmDexProfileSearchPayloadFilter) {
	s.Filter = filter
	s.require(searchTokenProfilesDexRequestFieldFilter)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetSort(sort *api.EvmDexProfileSearchPayloadSort) {
	s.Sort = sort
	s.require(searchTokenProfilesDexRequestFieldSort)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetOptions(options *api.EvmDexTokenProfilePayloadOptions) {
	s.Options = options
	s.require(searchTokenProfilesDexRequestFieldOptions)
}

func (s *SearchTokenProfilesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchTokenProfilesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchTokenProfilesDexRequest(body)
	return nil
}

func (s *SearchTokenProfilesDexRequest) MarshalJSON() ([]byte, error) {
	type embed SearchTokenProfilesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchWalletProfilesDexRequestFieldChainID = big.NewInt(1 << 0)
	searchWalletProfilesDexRequestFieldQuery   = big.NewInt(1 << 1)
	searchWalletProfilesDexRequestFieldFilter  = big.NewInt(1 << 2)
	searchWalletProfilesDexRequestFieldSort    = big.NewInt(1 << 3)
	searchWalletProfilesDexRequestFieldOptions = big.NewInt(1 << 4)
)

type SearchWalletProfilesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int                                        `json:"chain_id" url:"-"`
	Query   *api.EvmDexWalletProfileSearchPayloadQuery `json:"query,omitempty" url:"-"`
	Filter  *api.EvmDexProfileSearchPayloadFilter      `json:"filter,omitempty" url:"-"`
	Sort    *api.EvmDexProfileSearchPayloadSort        `json:"sort,omitempty" url:"-"`
	Options *api.EvmDexWalletProfilePayloadOptions     `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchWalletProfilesDexRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(searchWalletProfilesDexRequestFieldChainID)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetQuery(query *api.EvmDexWalletProfileSearchPayloadQuery) {
	s.Query = query
	s.require(searchWalletProfilesDexRequestFieldQuery)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetFilter(filter *api.EvmDexProfileSearchPayloadFilter) {
	s.Filter = filter
	s.require(searchWalletProfilesDexRequestFieldFilter)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetSort(sort *api.EvmDexProfileSearchPayloadSort) {
	s.Sort = sort
	s.require(searchWalletProfilesDexRequestFieldSort)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetOptions(options *api.EvmDexWalletProfilePayloadOptions) {
	s.Options = options
	s.require(searchWalletProfilesDexRequestFieldOptions)
}

func (s *SearchWalletProfilesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchWalletProfilesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchWalletProfilesDexRequest(body)
	return nil
}

func (s *SearchWalletProfilesDexRequest) MarshalJSON() ([]byte, error) {
	type embed SearchWalletProfilesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSwapsDexResponseFieldCount  = big.NewInt(1 << 0)
	getSwapsDexResponseFieldCursor = big.NewInt(1 << 1)
	getSwapsDexResponseFieldData   = big.NewInt(1 << 2)
)

type GetSwapsDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string           `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.EvmDexSwap `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSwapsDexResponse) GetCount() *int {
	if g == nil {
		return nil
	}
	return g.Count
}

func (g *GetSwapsDexResponse) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetSwapsDexResponse) GetData() []*api.EvmDexSwap {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetSwapsDexResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSwapsDexResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetCount(count *int) {
	g.Count = count
	g.require(getSwapsDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getSwapsDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetData(data []*api.EvmDexSwap) {
	g.Data = data
	g.require(getSwapsDexResponseFieldData)
}

func (g *GetSwapsDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSwapsDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSwapsDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSwapsDexResponse) MarshalJSON() ([]byte, error) {
	type embed GetSwapsDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSwapsDexResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getTradesDexResponseFieldCount  = big.NewInt(1 << 0)
	getTradesDexResponseFieldCursor = big.NewInt(1 << 1)
	getTradesDexResponseFieldData   = big.NewInt(1 << 2)
)

type GetTradesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string            `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.EvmDexTrade `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetTradesDexResponse) GetCount() *int {
	if g == nil {
		return nil
	}
	return g.Count
}

func (g *GetTradesDexResponse) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetTradesDexResponse) GetData() []*api.EvmDexTrade {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetTradesDexResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetTradesDexResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetCount(count *int) {
	g.Count = count
	g.require(getTradesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getTradesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetData(data []*api.EvmDexTrade) {
	g.Data = data
	g.require(getTradesDexResponseFieldData)
}

func (g *GetTradesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTradesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTradesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTradesDexResponse) MarshalJSON() ([]byte, error) {
	type embed GetTradesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetTradesDexResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	searchPositionProfilesDexResponseFieldCount  = big.NewInt(1 << 0)
	searchPositionProfilesDexResponseFieldCursor = big.NewInt(1 << 1)
	searchPositionProfilesDexResponseFieldData   = big.NewInt(1 << 2)
)

type SearchPositionProfilesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string                      `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.EvmDexPositionProfile `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchPositionProfilesDexResponse) GetCount() *int {
	if s == nil {
		return nil
	}
	return s.Count
}

func (s *SearchPositionProfilesDexResponse) GetCursor() *string {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchPositionProfilesDexResponse) GetData() []*api.EvmDexPositionProfile {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SearchPositionProfilesDexResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchPositionProfilesDexResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexResponse) SetCount(count *int) {
	s.Count = count
	s.require(searchPositionProfilesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexResponse) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchPositionProfilesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPositionProfilesDexResponse) SetData(data []*api.EvmDexPositionProfile) {
	s.Data = data
	s.require(searchPositionProfilesDexResponseFieldData)
}

func (s *SearchPositionProfilesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchPositionProfilesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchPositionProfilesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchPositionProfilesDexResponse) MarshalJSON() ([]byte, error) {
	type embed SearchPositionProfilesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchPositionProfilesDexResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	searchTokenProfilesDexResponseFieldCount  = big.NewInt(1 << 0)
	searchTokenProfilesDexResponseFieldCursor = big.NewInt(1 << 1)
	searchTokenProfilesDexResponseFieldData   = big.NewInt(1 << 2)
)

type SearchTokenProfilesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string                   `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.EvmDexTokenProfile `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchTokenProfilesDexResponse) GetCount() *int {
	if s == nil {
		return nil
	}
	return s.Count
}

func (s *SearchTokenProfilesDexResponse) GetCursor() *string {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchTokenProfilesDexResponse) GetData() []*api.EvmDexTokenProfile {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SearchTokenProfilesDexResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchTokenProfilesDexResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetCount(count *int) {
	s.Count = count
	s.require(searchTokenProfilesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchTokenProfilesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetData(data []*api.EvmDexTokenProfile) {
	s.Data = data
	s.require(searchTokenProfilesDexResponseFieldData)
}

func (s *SearchTokenProfilesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchTokenProfilesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchTokenProfilesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchTokenProfilesDexResponse) MarshalJSON() ([]byte, error) {
	type embed SearchTokenProfilesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchTokenProfilesDexResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	searchWalletProfilesDexResponseFieldCount  = big.NewInt(1 << 0)
	searchWalletProfilesDexResponseFieldCursor = big.NewInt(1 << 1)
	searchWalletProfilesDexResponseFieldData   = big.NewInt(1 << 2)
)

type SearchWalletProfilesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string                    `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.EvmDexWalletProfile `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchWalletProfilesDexResponse) GetCount() *int {
	if s == nil {
		return nil
	}
	return s.Count
}

func (s *SearchWalletProfilesDexResponse) GetCursor() *string {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchWalletProfilesDexResponse) GetData() []*api.EvmDexWalletProfile {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SearchWalletProfilesDexResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchWalletProfilesDexResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetCount(count *int) {
	s.Count = count
	s.require(searchWalletProfilesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchWalletProfilesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetData(data []*api.EvmDexWalletProfile) {
	s.Data = data
	s.require(searchWalletProfilesDexResponseFieldData)
}

func (s *SearchWalletProfilesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchWalletProfilesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchWalletProfilesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchWalletProfilesDexResponse) MarshalJSON() ([]byte, error) {
	type embed SearchWalletProfilesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchWalletProfilesDexResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
