// Code generated by Fern. DO NOT EDIT.

package solana

import (
	json "encoding/json"
	fmt "fmt"
	api "github.com/prism-api/sdk-go/api"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	getPriceDexRequestFieldTokens = big.NewInt(1 << 0)
)

type GetPriceDexRequest struct {
	// Token addresses to retrieve the latest prices for. Accepts between 1 and 1000 tokens per request.
	Tokens []string `json:"tokens" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceDexRequestFieldTokens)
}

func (g *GetPriceDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceDexRequest(body)
	return nil
}

func (g *GetPriceDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceCandlesDexRequestFieldToken    = big.NewInt(1 << 0)
	getPriceCandlesDexRequestFieldFrom     = big.NewInt(1 << 1)
	getPriceCandlesDexRequestFieldTo       = big.NewInt(1 << 2)
	getPriceCandlesDexRequestFieldCount    = big.NewInt(1 << 3)
	getPriceCandlesDexRequestFieldInterval = big.NewInt(1 << 4)
)

type GetPriceCandlesDexRequest struct {
	// Token address to retrieve price candles for.
	Token string `json:"token" url:"-"`
	// Start of the candle range, as a date-time RFC3339 string.
	// Must be combined with `to` to define a bounded range.
	From *time.Time `json:"from,omitempty" url:"-"`
	// End of the candle range, as a date-time RFC3339 string. Defaults to the current time.
	// Must be combined with either `from` (to define a bounded range) or `count` (to return the N most recent candles ending at `to`).
	To *time.Time `json:"to,omitempty" url:"-"`
	// Number of candles to return, ending at `to`.
	// Must be combined with `to`.
	Count *int `json:"count,omitempty" url:"-"`
	// Sampling interval between data points, in seconds.
	Interval int `json:"interval" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceCandlesDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetToken(token string) {
	g.Token = token
	g.require(getPriceCandlesDexRequestFieldToken)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetFrom(from *time.Time) {
	g.From = from
	g.require(getPriceCandlesDexRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetTo(to *time.Time) {
	g.To = to
	g.require(getPriceCandlesDexRequestFieldTo)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetCount(count *int) {
	g.Count = count
	g.require(getPriceCandlesDexRequestFieldCount)
}

// SetInterval sets the Interval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceCandlesDexRequest) SetInterval(interval int) {
	g.Interval = interval
	g.require(getPriceCandlesDexRequestFieldInterval)
}

func (g *GetPriceCandlesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceCandlesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceCandlesDexRequest(body)
	return nil
}

func (g *GetPriceCandlesDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceCandlesDexRequest
	var marshaler = struct {
		embed
		From *internal.DateTime `json:"from,omitempty"`
		To   *internal.DateTime `json:"to,omitempty"`
	}{
		embed: embed(*g),
		From:  internal.NewOptionalDateTime(g.From),
		To:    internal.NewOptionalDateTime(g.To),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceHistoryDexRequestFieldTokens   = big.NewInt(1 << 0)
	getPriceHistoryDexRequestFieldFrom     = big.NewInt(1 << 1)
	getPriceHistoryDexRequestFieldTo       = big.NewInt(1 << 2)
	getPriceHistoryDexRequestFieldInterval = big.NewInt(1 << 3)
)

type GetPriceHistoryDexRequest struct {
	// Token addresses to retrieve price history for. Accepts between 1 and 100 tokens per request.
	Tokens []string `json:"tokens" url:"-"`
	// Start of the history range, as a date-time RFC3339 string.
	From time.Time `json:"from" url:"-"`
	// End of the history range, as a date-time RFC3339 string. Defaults to the current time.
	To *time.Time `json:"to,omitempty" url:"-"`
	// Sampling interval between data points, in seconds.
	Interval int `json:"interval" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceHistoryDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceHistoryDexRequestFieldTokens)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetFrom(from time.Time) {
	g.From = from
	g.require(getPriceHistoryDexRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetTo(to *time.Time) {
	g.To = to
	g.require(getPriceHistoryDexRequestFieldTo)
}

// SetInterval sets the Interval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceHistoryDexRequest) SetInterval(interval int) {
	g.Interval = interval
	g.require(getPriceHistoryDexRequestFieldInterval)
}

func (g *GetPriceHistoryDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceHistoryDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceHistoryDexRequest(body)
	return nil
}

func (g *GetPriceHistoryDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceHistoryDexRequest
	var marshaler = struct {
		embed
		From *internal.DateTime `json:"from"`
		To   *internal.DateTime `json:"to,omitempty"`
	}{
		embed: embed(*g),
		From:  internal.NewDateTime(g.From),
		To:    internal.NewOptionalDateTime(g.To),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPriceStatsDexRequestFieldTokens = big.NewInt(1 << 0)
)

type GetPriceStatsDexRequest struct {
	// Token addresses to retrieve price statistics for. Accepts between 1 and 1000 tokens per request.
	Tokens []string `json:"tokens" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPriceStatsDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPriceStatsDexRequest) SetTokens(tokens []string) {
	g.Tokens = tokens
	g.require(getPriceStatsDexRequestFieldTokens)
}

func (g *GetPriceStatsDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPriceStatsDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetPriceStatsDexRequest(body)
	return nil
}

func (g *GetPriceStatsDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetPriceStatsDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSwapsDexRequestFieldWallet = big.NewInt(1 << 0)
	getSwapsDexRequestFieldToken  = big.NewInt(1 << 1)
)

type GetSwapsDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Wallet address to filter swaps by. When combined with `token`, returns only swaps for that wallet on that token.
	Wallet *string `json:"wallet,omitempty" url:"-"`
	// Token address to filter swaps by. When combined with `wallet`, returns only swaps for that wallet on that token.
	Token *string `json:"token,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSwapsDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetWallet(wallet *string) {
	g.Wallet = wallet
	g.require(getSwapsDexRequestFieldWallet)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexRequest) SetToken(token *string) {
	g.Token = token
	g.require(getSwapsDexRequestFieldToken)
}

func (g *GetSwapsDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSwapsDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetSwapsDexRequest(body)
	return nil
}

func (g *GetSwapsDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetSwapsDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getTokenProfileDexRequestFieldToken   = big.NewInt(1 << 0)
	getTokenProfileDexRequestFieldOptions = big.NewInt(1 << 1)
)

type GetTokenProfileDexRequest struct {
	// Token address to retrieve the profile for.
	Token   string                                   `json:"token" url:"-"`
	Options *api.SolanaDexTokenProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTokenProfileDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTokenProfileDexRequest) SetToken(token string) {
	g.Token = token
	g.require(getTokenProfileDexRequestFieldToken)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTokenProfileDexRequest) SetOptions(options *api.SolanaDexTokenProfilePayloadOptions) {
	g.Options = options
	g.require(getTokenProfileDexRequestFieldOptions)
}

func (g *GetTokenProfileDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTokenProfileDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetTokenProfileDexRequest(body)
	return nil
}

func (g *GetTokenProfileDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetTokenProfileDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getTradesDexRequestFieldWallet = big.NewInt(1 << 0)
	getTradesDexRequestFieldToken  = big.NewInt(1 << 1)
)

type GetTradesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor *string `json:"cursor,omitempty" url:"-"`
	// Wallet address to filter trades by. When combined with `token`, returns only trades for that wallet on that token.
	Wallet *string `json:"wallet,omitempty" url:"-"`
	// Token address to filter trades by. When combined with `wallet`, returns only trades for that wallet on that token.
	Token *string `json:"token,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTradesDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexRequest) SetWallet(wallet *string) {
	g.Wallet = wallet
	g.require(getTradesDexRequestFieldWallet)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexRequest) SetToken(token *string) {
	g.Token = token
	g.require(getTradesDexRequestFieldToken)
}

func (g *GetTradesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTradesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetTradesDexRequest(body)
	return nil
}

func (g *GetTradesDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetTradesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getWalletProfileDexRequestFieldWallet  = big.NewInt(1 << 0)
	getWalletProfileDexRequestFieldOptions = big.NewInt(1 << 1)
)

type GetWalletProfileDexRequest struct {
	// Wallet address to retrieve the profile for.
	Wallet  string                                    `json:"wallet" url:"-"`
	Options *api.SolanaDexWalletProfilePayloadOptions `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWalletProfileDexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetWallet sets the Wallet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletProfileDexRequest) SetWallet(wallet string) {
	g.Wallet = wallet
	g.require(getWalletProfileDexRequestFieldWallet)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletProfileDexRequest) SetOptions(options *api.SolanaDexWalletProfilePayloadOptions) {
	g.Options = options
	g.require(getWalletProfileDexRequestFieldOptions)
}

func (g *GetWalletProfileDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetWalletProfileDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetWalletProfileDexRequest(body)
	return nil
}

func (g *GetWalletProfileDexRequest) MarshalJSON() ([]byte, error) {
	type embed GetWalletProfileDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchTokenProfilesDexRequestFieldQuery         = big.NewInt(1 << 0)
	searchTokenProfilesDexRequestFieldFilter        = big.NewInt(1 << 1)
	searchTokenProfilesDexRequestFieldSort          = big.NewInt(1 << 2)
	searchTokenProfilesDexRequestFieldDynamicLabels = big.NewInt(1 << 3)
	searchTokenProfilesDexRequestFieldOptions       = big.NewInt(1 << 4)
)

type SearchTokenProfilesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor        *string                                           `json:"cursor,omitempty" url:"-"`
	Query         *api.SolanaDexTokenProfileSearchPayloadQueryField `json:"query,omitempty" url:"-"`
	Filter        *api.SolanaDexProfileSearchPayloadFilter          `json:"filter,omitempty" url:"-"`
	Sort          *api.SolanaDexProfileSearchPayloadSort            `json:"sort,omitempty" url:"-"`
	DynamicLabels *api.SolanaDexProfileSearchPayloadDynamicLabels   `json:"dynamic_labels,omitempty" url:"-"`
	Options       *api.SolanaDexTokenProfilePayloadOptions          `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchTokenProfilesDexRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetQuery(query *api.SolanaDexTokenProfileSearchPayloadQueryField) {
	s.Query = query
	s.require(searchTokenProfilesDexRequestFieldQuery)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetFilter(filter *api.SolanaDexProfileSearchPayloadFilter) {
	s.Filter = filter
	s.require(searchTokenProfilesDexRequestFieldFilter)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetSort(sort *api.SolanaDexProfileSearchPayloadSort) {
	s.Sort = sort
	s.require(searchTokenProfilesDexRequestFieldSort)
}

// SetDynamicLabels sets the DynamicLabels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetDynamicLabels(dynamicLabels *api.SolanaDexProfileSearchPayloadDynamicLabels) {
	s.DynamicLabels = dynamicLabels
	s.require(searchTokenProfilesDexRequestFieldDynamicLabels)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexRequest) SetOptions(options *api.SolanaDexTokenProfilePayloadOptions) {
	s.Options = options
	s.require(searchTokenProfilesDexRequestFieldOptions)
}

func (s *SearchTokenProfilesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchTokenProfilesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchTokenProfilesDexRequest(body)
	return nil
}

func (s *SearchTokenProfilesDexRequest) MarshalJSON() ([]byte, error) {
	type embed SearchTokenProfilesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchWalletProfilesDexRequestFieldQuery         = big.NewInt(1 << 0)
	searchWalletProfilesDexRequestFieldFilter        = big.NewInt(1 << 1)
	searchWalletProfilesDexRequestFieldSort          = big.NewInt(1 << 2)
	searchWalletProfilesDexRequestFieldDynamicLabels = big.NewInt(1 << 3)
	searchWalletProfilesDexRequestFieldOptions       = big.NewInt(1 << 4)
)

type SearchWalletProfilesDexRequest struct {
	// Maximum number of results to return in a single page.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Opaque cursor returned by a previous response. Pass it to fetch the next page of results.
	Cursor        *string                                         `json:"cursor,omitempty" url:"-"`
	Query         *api.SolanaDexWalletProfileSearchPayloadQuery   `json:"query,omitempty" url:"-"`
	Filter        *api.SolanaDexProfileSearchPayloadFilter        `json:"filter,omitempty" url:"-"`
	Sort          *api.SolanaDexProfileSearchPayloadSort          `json:"sort,omitempty" url:"-"`
	DynamicLabels *api.SolanaDexProfileSearchPayloadDynamicLabels `json:"dynamic_labels,omitempty" url:"-"`
	Options       *api.SolanaDexWalletProfilePayloadOptions       `json:"options,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchWalletProfilesDexRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetQuery(query *api.SolanaDexWalletProfileSearchPayloadQuery) {
	s.Query = query
	s.require(searchWalletProfilesDexRequestFieldQuery)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetFilter(filter *api.SolanaDexProfileSearchPayloadFilter) {
	s.Filter = filter
	s.require(searchWalletProfilesDexRequestFieldFilter)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetSort(sort *api.SolanaDexProfileSearchPayloadSort) {
	s.Sort = sort
	s.require(searchWalletProfilesDexRequestFieldSort)
}

// SetDynamicLabels sets the DynamicLabels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetDynamicLabels(dynamicLabels *api.SolanaDexProfileSearchPayloadDynamicLabels) {
	s.DynamicLabels = dynamicLabels
	s.require(searchWalletProfilesDexRequestFieldDynamicLabels)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexRequest) SetOptions(options *api.SolanaDexWalletProfilePayloadOptions) {
	s.Options = options
	s.require(searchWalletProfilesDexRequestFieldOptions)
}

func (s *SearchWalletProfilesDexRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchWalletProfilesDexRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchWalletProfilesDexRequest(body)
	return nil
}

func (s *SearchWalletProfilesDexRequest) MarshalJSON() ([]byte, error) {
	type embed SearchWalletProfilesDexRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSwapsDexResponseFieldCount  = big.NewInt(1 << 0)
	getSwapsDexResponseFieldCursor = big.NewInt(1 << 1)
	getSwapsDexResponseFieldData   = big.NewInt(1 << 2)
)

type GetSwapsDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string              `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.SolanaDexSwap `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSwapsDexResponse) GetCount() *int {
	if g == nil {
		return nil
	}
	return g.Count
}

func (g *GetSwapsDexResponse) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetSwapsDexResponse) GetData() []*api.SolanaDexSwap {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetSwapsDexResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSwapsDexResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetCount(count *int) {
	g.Count = count
	g.require(getSwapsDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getSwapsDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSwapsDexResponse) SetData(data []*api.SolanaDexSwap) {
	g.Data = data
	g.require(getSwapsDexResponseFieldData)
}

func (g *GetSwapsDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSwapsDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSwapsDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSwapsDexResponse) MarshalJSON() ([]byte, error) {
	type embed GetSwapsDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSwapsDexResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getTradesDexResponseFieldCount  = big.NewInt(1 << 0)
	getTradesDexResponseFieldCursor = big.NewInt(1 << 1)
	getTradesDexResponseFieldData   = big.NewInt(1 << 2)
)

type GetTradesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string               `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.SolanaDexTrade `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetTradesDexResponse) GetCount() *int {
	if g == nil {
		return nil
	}
	return g.Count
}

func (g *GetTradesDexResponse) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetTradesDexResponse) GetData() []*api.SolanaDexTrade {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetTradesDexResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetTradesDexResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetCount(count *int) {
	g.Count = count
	g.require(getTradesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getTradesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTradesDexResponse) SetData(data []*api.SolanaDexTrade) {
	g.Data = data
	g.require(getTradesDexResponseFieldData)
}

func (g *GetTradesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTradesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTradesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTradesDexResponse) MarshalJSON() ([]byte, error) {
	type embed GetTradesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetTradesDexResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	searchTokenProfilesDexResponseFieldCount  = big.NewInt(1 << 0)
	searchTokenProfilesDexResponseFieldCursor = big.NewInt(1 << 1)
	searchTokenProfilesDexResponseFieldData   = big.NewInt(1 << 2)
)

type SearchTokenProfilesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string                      `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.SolanaDexTokenProfile `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchTokenProfilesDexResponse) GetCount() *int {
	if s == nil {
		return nil
	}
	return s.Count
}

func (s *SearchTokenProfilesDexResponse) GetCursor() *string {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchTokenProfilesDexResponse) GetData() []*api.SolanaDexTokenProfile {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SearchTokenProfilesDexResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchTokenProfilesDexResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetCount(count *int) {
	s.Count = count
	s.require(searchTokenProfilesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchTokenProfilesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchTokenProfilesDexResponse) SetData(data []*api.SolanaDexTokenProfile) {
	s.Data = data
	s.require(searchTokenProfilesDexResponseFieldData)
}

func (s *SearchTokenProfilesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchTokenProfilesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchTokenProfilesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchTokenProfilesDexResponse) MarshalJSON() ([]byte, error) {
	type embed SearchTokenProfilesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchTokenProfilesDexResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	searchWalletProfilesDexResponseFieldCount  = big.NewInt(1 << 0)
	searchWalletProfilesDexResponseFieldCursor = big.NewInt(1 << 1)
	searchWalletProfilesDexResponseFieldData   = big.NewInt(1 << 2)
)

type SearchWalletProfilesDexResponse struct {
	// Total number of matching items
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Cursor for pagination
	Cursor *string                       `json:"cursor,omitempty" url:"cursor,omitempty"`
	Data   []*api.SolanaDexWalletProfile `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchWalletProfilesDexResponse) GetCount() *int {
	if s == nil {
		return nil
	}
	return s.Count
}

func (s *SearchWalletProfilesDexResponse) GetCursor() *string {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchWalletProfilesDexResponse) GetData() []*api.SolanaDexWalletProfile {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SearchWalletProfilesDexResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchWalletProfilesDexResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetCount(count *int) {
	s.Count = count
	s.require(searchWalletProfilesDexResponseFieldCount)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchWalletProfilesDexResponseFieldCursor)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchWalletProfilesDexResponse) SetData(data []*api.SolanaDexWalletProfile) {
	s.Data = data
	s.require(searchWalletProfilesDexResponseFieldData)
}

func (s *SearchWalletProfilesDexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchWalletProfilesDexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchWalletProfilesDexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchWalletProfilesDexResponse) MarshalJSON() ([]byte, error) {
	type embed SearchWalletProfilesDexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchWalletProfilesDexResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
