// Code generated by Fern. DO NOT EDIT.

package dex

import (
	context "context"

	api "github.com/prism-api/sdk-go/api"
	evm "github.com/prism-api/sdk-go/api/evm"
	core "github.com/prism-api/sdk-go/core"
	internal "github.com/prism-api/sdk-go/internal"
	option "github.com/prism-api/sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a wallet profile for a specific wallet.
func (c *Client) GetWalletProfile(
	ctx context.Context,
	request *evm.GetWalletProfileDexRequest,
	opts ...option.RequestOption,
) (*api.EvmDexWalletProfile, error) {
	response, err := c.WithRawResponse.GetWalletProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter, query, and sort wallet profiles based on specified metrics and conditions.
func (c *Client) SearchWalletProfiles(
	ctx context.Context,
	request *evm.SearchWalletProfilesDexRequest,
	opts ...option.RequestOption,
) (*evm.SearchWalletProfilesDexResponse, error) {
	response, err := c.WithRawResponse.SearchWalletProfiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the profile for a specific token.
func (c *Client) GetTokenProfile(
	ctx context.Context,
	request *evm.GetTokenProfileDexRequest,
	opts ...option.RequestOption,
) (*api.EvmDexTokenProfile, error) {
	response, err := c.WithRawResponse.GetTokenProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter, query, and sort token profiles based on specified metrics and conditions.
func (c *Client) SearchTokenProfiles(
	ctx context.Context,
	request *evm.SearchTokenProfilesDexRequest,
	opts ...option.RequestOption,
) (*evm.SearchTokenProfilesDexResponse, error) {
	response, err := c.WithRawResponse.SearchTokenProfiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a position profile for a specific wallet-token pair.
func (c *Client) GetPositionProfile(
	ctx context.Context,
	request *evm.GetPositionProfileDexRequest,
	opts ...option.RequestOption,
) (*api.EvmDexPositionProfile, error) {
	response, err := c.WithRawResponse.GetPositionProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter, query, and sort position profiles based on specified metrics and conditions.
func (c *Client) SearchPositionProfiles(
	ctx context.Context,
	request *evm.SearchPositionProfilesDexRequest,
	opts ...option.RequestOption,
) (*evm.SearchPositionProfilesDexResponse, error) {
	response, err := c.WithRawResponse.SearchPositionProfiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns trades for a wallet and/or token on a single chain.
func (c *Client) GetTrades(
	ctx context.Context,
	request *evm.GetTradesDexRequest,
	opts ...option.RequestOption,
) (*evm.GetTradesDexResponse, error) {
	response, err := c.WithRawResponse.GetTrades(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns swaps for a combination of wallet, token and/or pool.
func (c *Client) GetSwaps(
	ctx context.Context,
	request *evm.GetSwapsDexRequest,
	opts ...option.RequestOption,
) (*evm.GetSwapsDexResponse, error) {
	response, err := c.WithRawResponse.GetSwaps(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns prices for one or more tokens or pools.
func (c *Client) GetPrice(
	ctx context.Context,
	request *evm.GetPriceDexRequest,
	opts ...option.RequestOption,
) ([]*api.EvmDexPrice, error) {
	response, err := c.WithRawResponse.GetPrice(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price stats for one or more tokens or pools.
func (c *Client) GetPriceStats(
	ctx context.Context,
	request *evm.GetPriceStatsDexRequest,
	opts ...option.RequestOption,
) ([]*api.EvmDexPriceStats, error) {
	response, err := c.WithRawResponse.GetPriceStats(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price candles for a specific token and/or pool.
func (c *Client) GetPriceCandles(
	ctx context.Context,
	request *evm.GetPriceCandlesDexRequest,
	opts ...option.RequestOption,
) ([]*api.EvmDexPriceCandle, error) {
	response, err := c.WithRawResponse.GetPriceCandles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns price history for one or more tokens or pools.
func (c *Client) GetPriceHistory(
	ctx context.Context,
	request *evm.GetPriceHistoryDexRequest,
	opts ...option.RequestOption,
) ([]*api.EvmDexPriceHistory, error) {
	response, err := c.WithRawResponse.GetPriceHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
