// Code generated by Fern. DO NOT EDIT.

package websocket

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/prism-api/sdk-go/internal"
	big "math/big"
)

var (
	subscribeEvmAssetsTransfersParamsFieldChainID       = big.NewInt(1 << 0)
	subscribeEvmAssetsTransfersParamsFieldFromAddresses = big.NewInt(1 << 1)
	subscribeEvmAssetsTransfersParamsFieldToAddresses   = big.NewInt(1 << 2)
)

type SubscribeEvmAssetsTransfersParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The from addresses to filter by. Leave empty to subscribe to all from addresses on the chain.
	FromAddresses []string `json:"from_addresses,omitempty" url:"from_addresses,omitempty"`
	// The to addresses to filter by. Leave empty to subscribe to all to addresses on the chain.
	ToAddresses []string `json:"to_addresses,omitempty" url:"to_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmAssetsTransfersParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmAssetsTransfersParams) GetFromAddresses() []string {
	if s == nil {
		return nil
	}
	return s.FromAddresses
}

func (s *SubscribeEvmAssetsTransfersParams) GetToAddresses() []string {
	if s == nil {
		return nil
	}
	return s.ToAddresses
}

func (s *SubscribeEvmAssetsTransfersParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmAssetsTransfersParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmAssetsTransfersParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmAssetsTransfersParamsFieldChainID)
}

// SetFromAddresses sets the FromAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmAssetsTransfersParams) SetFromAddresses(fromAddresses []string) {
	s.FromAddresses = fromAddresses
	s.require(subscribeEvmAssetsTransfersParamsFieldFromAddresses)
}

// SetToAddresses sets the ToAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmAssetsTransfersParams) SetToAddresses(toAddresses []string) {
	s.ToAddresses = toAddresses
	s.require(subscribeEvmAssetsTransfersParamsFieldToAddresses)
}

func (s *SubscribeEvmAssetsTransfersParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmAssetsTransfersParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmAssetsTransfersParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmAssetsTransfersParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmAssetsTransfersParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmAssetsTransfersParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexPoolsParamsFieldChainID       = big.NewInt(1 << 0)
	subscribeEvmDexPoolsParamsFieldPoolAddresses = big.NewInt(1 << 1)
)

type SubscribeEvmDexPoolsParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The pool addresses to filter by. Unlike the other EVM subscriptions, an empty list
	// matches no pools rather than all of them, so at least one address is required to
	// receive updates.
	PoolAddresses []string `json:"pool_addresses,omitempty" url:"pool_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexPoolsParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexPoolsParams) GetPoolAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PoolAddresses
}

func (s *SubscribeEvmDexPoolsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexPoolsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexPoolsParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexPoolsParamsFieldChainID)
}

// SetPoolAddresses sets the PoolAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexPoolsParams) SetPoolAddresses(poolAddresses []string) {
	s.PoolAddresses = poolAddresses
	s.require(subscribeEvmDexPoolsParamsFieldPoolAddresses)
}

func (s *SubscribeEvmDexPoolsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexPoolsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexPoolsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexPoolsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexPoolsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexPoolsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexPricesParamsFieldChainID        = big.NewInt(1 << 0)
	subscribeEvmDexPricesParamsFieldTokenAddresses = big.NewInt(1 << 1)
	subscribeEvmDexPricesParamsFieldPoolAddresses  = big.NewInt(1 << 2)
)

type SubscribeEvmDexPricesParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens on the chain.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`
	// The pool addresses to filter by. Leave empty to subscribe to all pools on the chain.
	PoolAddresses []string `json:"pool_addresses,omitempty" url:"pool_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexPricesParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexPricesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeEvmDexPricesParams) GetPoolAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PoolAddresses
}

func (s *SubscribeEvmDexPricesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexPricesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexPricesParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexPricesParamsFieldChainID)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexPricesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeEvmDexPricesParamsFieldTokenAddresses)
}

// SetPoolAddresses sets the PoolAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexPricesParams) SetPoolAddresses(poolAddresses []string) {
	s.PoolAddresses = poolAddresses
	s.require(subscribeEvmDexPricesParamsFieldPoolAddresses)
}

func (s *SubscribeEvmDexPricesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexPricesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexPricesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexPricesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexPricesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexPricesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexSwapsParamsFieldChainID         = big.NewInt(1 << 0)
	subscribeEvmDexSwapsParamsFieldWalletAddresses = big.NewInt(1 << 1)
	subscribeEvmDexSwapsParamsFieldTokenAddresses  = big.NewInt(1 << 2)
	subscribeEvmDexSwapsParamsFieldPoolAddresses   = big.NewInt(1 << 3)
)

type SubscribeEvmDexSwapsParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets on the chain.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens on the chain.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`
	// The pool addresses to filter by. Leave empty to subscribe to all pools on the chain.
	PoolAddresses []string `json:"pool_addresses,omitempty" url:"pool_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexSwapsParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexSwapsParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeEvmDexSwapsParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeEvmDexSwapsParams) GetPoolAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PoolAddresses
}

func (s *SubscribeEvmDexSwapsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexSwapsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexSwapsParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexSwapsParamsFieldChainID)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexSwapsParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeEvmDexSwapsParamsFieldWalletAddresses)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexSwapsParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeEvmDexSwapsParamsFieldTokenAddresses)
}

// SetPoolAddresses sets the PoolAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexSwapsParams) SetPoolAddresses(poolAddresses []string) {
	s.PoolAddresses = poolAddresses
	s.require(subscribeEvmDexSwapsParamsFieldPoolAddresses)
}

func (s *SubscribeEvmDexSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexSwapsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexSwapsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexTokenProfilesParamsFieldChainID        = big.NewInt(1 << 0)
	subscribeEvmDexTokenProfilesParamsFieldTokenAddresses = big.NewInt(1 << 1)
)

type SubscribeEvmDexTokenProfilesParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens on the chain.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexTokenProfilesParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexTokenProfilesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeEvmDexTokenProfilesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexTokenProfilesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexTokenProfilesParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexTokenProfilesParamsFieldChainID)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexTokenProfilesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeEvmDexTokenProfilesParamsFieldTokenAddresses)
}

func (s *SubscribeEvmDexTokenProfilesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexTokenProfilesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexTokenProfilesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexTokenProfilesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexTokenProfilesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexTokenProfilesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexTradesParamsFieldChainID         = big.NewInt(1 << 0)
	subscribeEvmDexTradesParamsFieldTokenAddresses  = big.NewInt(1 << 1)
	subscribeEvmDexTradesParamsFieldWalletAddresses = big.NewInt(1 << 2)
)

type SubscribeEvmDexTradesParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens on the chain.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets on the chain.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexTradesParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexTradesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeEvmDexTradesParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeEvmDexTradesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexTradesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexTradesParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexTradesParamsFieldChainID)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexTradesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeEvmDexTradesParamsFieldTokenAddresses)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexTradesParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeEvmDexTradesParamsFieldWalletAddresses)
}

func (s *SubscribeEvmDexTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexTradesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexTradesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeEvmDexWalletProfilesParamsFieldChainID         = big.NewInt(1 << 0)
	subscribeEvmDexWalletProfilesParamsFieldWalletAddresses = big.NewInt(1 << 1)
)

type SubscribeEvmDexWalletProfilesParams struct {
	// Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains).
	ChainID int `json:"chain_id" url:"chain_id"`
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets on the chain.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeEvmDexWalletProfilesParams) GetChainID() int {
	if s == nil {
		return 0
	}
	return s.ChainID
}

func (s *SubscribeEvmDexWalletProfilesParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeEvmDexWalletProfilesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeEvmDexWalletProfilesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetChainID sets the ChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexWalletProfilesParams) SetChainID(chainID int) {
	s.ChainID = chainID
	s.require(subscribeEvmDexWalletProfilesParamsFieldChainID)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeEvmDexWalletProfilesParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeEvmDexWalletProfilesParamsFieldWalletAddresses)
}

func (s *SubscribeEvmDexWalletProfilesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeEvmDexWalletProfilesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeEvmDexWalletProfilesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeEvmDexWalletProfilesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeEvmDexWalletProfilesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeEvmDexWalletProfilesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaAssetsBalanceChangesParamsFieldOwnerAddresses = big.NewInt(1 << 0)
	subscribeSolanaAssetsBalanceChangesParamsFieldTokenAddresses = big.NewInt(1 << 1)
)

type SubscribeSolanaAssetsBalanceChangesParams struct {
	// The owner addresses to filter by. Leave empty to subscribe to all owners.
	OwnerAddresses []string `json:"owner_addresses,omitempty" url:"owner_addresses,omitempty"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) GetOwnerAddresses() []string {
	if s == nil {
		return nil
	}
	return s.OwnerAddresses
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetOwnerAddresses sets the OwnerAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaAssetsBalanceChangesParams) SetOwnerAddresses(ownerAddresses []string) {
	s.OwnerAddresses = ownerAddresses
	s.require(subscribeSolanaAssetsBalanceChangesParamsFieldOwnerAddresses)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaAssetsBalanceChangesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeSolanaAssetsBalanceChangesParamsFieldTokenAddresses)
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaAssetsBalanceChangesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaAssetsBalanceChangesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaAssetsBalanceChangesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaAssetsBalanceChangesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaAssetsTransfersParamsFieldFromAddresses = big.NewInt(1 << 0)
	subscribeSolanaAssetsTransfersParamsFieldToAddresses   = big.NewInt(1 << 1)
)

type SubscribeSolanaAssetsTransfersParams struct {
	// The from addresses to filter by. Leave empty to subscribe to all from addresses.
	FromAddresses []string `json:"from_addresses,omitempty" url:"from_addresses,omitempty"`
	// The to addresses to filter by. Leave empty to subscribe to all to addresses.
	ToAddresses []string `json:"to_addresses,omitempty" url:"to_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaAssetsTransfersParams) GetFromAddresses() []string {
	if s == nil {
		return nil
	}
	return s.FromAddresses
}

func (s *SubscribeSolanaAssetsTransfersParams) GetToAddresses() []string {
	if s == nil {
		return nil
	}
	return s.ToAddresses
}

func (s *SubscribeSolanaAssetsTransfersParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaAssetsTransfersParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetFromAddresses sets the FromAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaAssetsTransfersParams) SetFromAddresses(fromAddresses []string) {
	s.FromAddresses = fromAddresses
	s.require(subscribeSolanaAssetsTransfersParamsFieldFromAddresses)
}

// SetToAddresses sets the ToAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaAssetsTransfersParams) SetToAddresses(toAddresses []string) {
	s.ToAddresses = toAddresses
	s.require(subscribeSolanaAssetsTransfersParamsFieldToAddresses)
}

func (s *SubscribeSolanaAssetsTransfersParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaAssetsTransfersParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaAssetsTransfersParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaAssetsTransfersParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaAssetsTransfersParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaAssetsTransfersParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexPoolsParamsFieldPoolAddresses = big.NewInt(1 << 0)
)

type SubscribeSolanaDexPoolsParams struct {
	// The pool addresses to filter by. Leave empty to subscribe to all pools.
	PoolAddresses []string `json:"pool_addresses,omitempty" url:"pool_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexPoolsParams) GetPoolAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PoolAddresses
}

func (s *SubscribeSolanaDexPoolsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexPoolsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetPoolAddresses sets the PoolAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexPoolsParams) SetPoolAddresses(poolAddresses []string) {
	s.PoolAddresses = poolAddresses
	s.require(subscribeSolanaDexPoolsParamsFieldPoolAddresses)
}

func (s *SubscribeSolanaDexPoolsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexPoolsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexPoolsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexPoolsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexPoolsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexPoolsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexPositionProfilesParamsFieldPositionAddresses = big.NewInt(1 << 0)
)

type SubscribeSolanaDexPositionProfilesParams struct {
	// The position addresses to filter by. Leave empty to subscribe to all positions.
	PositionAddresses []string `json:"position_addresses,omitempty" url:"position_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexPositionProfilesParams) GetPositionAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PositionAddresses
}

func (s *SubscribeSolanaDexPositionProfilesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexPositionProfilesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetPositionAddresses sets the PositionAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexPositionProfilesParams) SetPositionAddresses(positionAddresses []string) {
	s.PositionAddresses = positionAddresses
	s.require(subscribeSolanaDexPositionProfilesParamsFieldPositionAddresses)
}

func (s *SubscribeSolanaDexPositionProfilesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexPositionProfilesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexPositionProfilesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexPositionProfilesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexPositionProfilesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexPositionProfilesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexPricesParamsFieldTokenAddresses = big.NewInt(1 << 0)
)

type SubscribeSolanaDexPricesParams struct {
	// The token addresses to filter by. Leave empty to subscribe to all tokens.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexPricesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeSolanaDexPricesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexPricesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexPricesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeSolanaDexPricesParamsFieldTokenAddresses)
}

func (s *SubscribeSolanaDexPricesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexPricesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexPricesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexPricesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexPricesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexPricesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexSwapsParamsFieldWalletAddresses = big.NewInt(1 << 0)
	subscribeSolanaDexSwapsParamsFieldTokenAddresses  = big.NewInt(1 << 1)
	subscribeSolanaDexSwapsParamsFieldPoolAddresses   = big.NewInt(1 << 2)
)

type SubscribeSolanaDexSwapsParams struct {
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`
	// The token addresses to filter by. Leave empty to subscribe to all tokens.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`
	// The pool addresses to filter by. Leave empty to subscribe to all pools.
	PoolAddresses []string `json:"pool_addresses,omitempty" url:"pool_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexSwapsParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeSolanaDexSwapsParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeSolanaDexSwapsParams) GetPoolAddresses() []string {
	if s == nil {
		return nil
	}
	return s.PoolAddresses
}

func (s *SubscribeSolanaDexSwapsParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexSwapsParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexSwapsParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeSolanaDexSwapsParamsFieldWalletAddresses)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexSwapsParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeSolanaDexSwapsParamsFieldTokenAddresses)
}

// SetPoolAddresses sets the PoolAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexSwapsParams) SetPoolAddresses(poolAddresses []string) {
	s.PoolAddresses = poolAddresses
	s.require(subscribeSolanaDexSwapsParamsFieldPoolAddresses)
}

func (s *SubscribeSolanaDexSwapsParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexSwapsParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexSwapsParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexSwapsParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexSwapsParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexSwapsParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexTokenProfilesParamsFieldTokenAddresses = big.NewInt(1 << 0)
)

type SubscribeSolanaDexTokenProfilesParams struct {
	// The token addresses to filter by. Leave empty to subscribe to all tokens.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexTokenProfilesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeSolanaDexTokenProfilesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexTokenProfilesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexTokenProfilesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeSolanaDexTokenProfilesParamsFieldTokenAddresses)
}

func (s *SubscribeSolanaDexTokenProfilesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexTokenProfilesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexTokenProfilesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexTokenProfilesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexTokenProfilesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexTokenProfilesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexTradesParamsFieldTokenAddresses  = big.NewInt(1 << 0)
	subscribeSolanaDexTradesParamsFieldWalletAddresses = big.NewInt(1 << 1)
)

type SubscribeSolanaDexTradesParams struct {
	// The token addresses to filter by. Leave empty to subscribe to all tokens.
	TokenAddresses []string `json:"token_addresses,omitempty" url:"token_addresses,omitempty"`
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexTradesParams) GetTokenAddresses() []string {
	if s == nil {
		return nil
	}
	return s.TokenAddresses
}

func (s *SubscribeSolanaDexTradesParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeSolanaDexTradesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexTradesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTokenAddresses sets the TokenAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexTradesParams) SetTokenAddresses(tokenAddresses []string) {
	s.TokenAddresses = tokenAddresses
	s.require(subscribeSolanaDexTradesParamsFieldTokenAddresses)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexTradesParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeSolanaDexTradesParamsFieldWalletAddresses)
}

func (s *SubscribeSolanaDexTradesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexTradesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexTradesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexTradesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexTradesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexTradesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	subscribeSolanaDexWalletProfilesParamsFieldWalletAddresses = big.NewInt(1 << 0)
)

type SubscribeSolanaDexWalletProfilesParams struct {
	// The wallet addresses to filter by. Leave empty to subscribe to all wallets.
	WalletAddresses []string `json:"wallet_addresses,omitempty" url:"wallet_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubscribeSolanaDexWalletProfilesParams) GetWalletAddresses() []string {
	if s == nil {
		return nil
	}
	return s.WalletAddresses
}

func (s *SubscribeSolanaDexWalletProfilesParams) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubscribeSolanaDexWalletProfilesParams) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWalletAddresses sets the WalletAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubscribeSolanaDexWalletProfilesParams) SetWalletAddresses(walletAddresses []string) {
	s.WalletAddresses = walletAddresses
	s.require(subscribeSolanaDexWalletProfilesParamsFieldWalletAddresses)
}

func (s *SubscribeSolanaDexWalletProfilesParams) UnmarshalJSON(data []byte) error {
	type unmarshaler SubscribeSolanaDexWalletProfilesParams
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubscribeSolanaDexWalletProfilesParams(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubscribeSolanaDexWalletProfilesParams) MarshalJSON() ([]byte, error) {
	type embed SubscribeSolanaDexWalletProfilesParams
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubscribeSolanaDexWalletProfilesParams) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
